import os
from scraper.archon_scraper import fetch_archon_data
from scraper.lua_writer import lua_table_string
from scraper.config import CLASSES_AND_SPECS, ICON_PATHS

def main():
    os.makedirs('data', exist_ok=True)
    for class_name, specs in CLASSES_AND_SPECS.items():
        class_data = {}
        for spec in specs:
            print(f"Fetching {class_name} {spec}...")
            # Get the icon from ICON_PATHS, fallback to empty string if not found
            icon = ICON_PATHS.get(class_name, {}).get(spec, "")
            class_data[spec.upper()] = fetch_archon_data(class_name, spec, icon=icon)
        with open(f"data/data_{class_name}.lua", "w", encoding="utf-8") as f:
            f.write("-- Auto-generated by scraper\n")
            f.write(f"WishListData_{class_name.capitalize()} = ")
            f.write(lua_table_string(class_data))
            f.write("\n")

if __name__ == "__main__":
    main()
