-- data_warrior.lua

WishListData_Warrior = {
    PROTECTION = {
        icon = "Interface/ICONS/Ability_Warrior_DefensiveStance",
        talent = "CkEAAAAAAAAAAAAAAAAAAAAAAIGAAAAmZmxMzMGzyMLzMzshxYEzyYGGLjZmhlZmxMwwAAAAAAAzYAALbLAAbmxwCMwMsQjZWA",
        statprio = "Strength > Crit > Haste > Mastery > Versatility",
        enchants = {
            HEAD = { id = 239095, icon = "Interface/ICONS/inv_helmet_02", name = "Greater Rune of the Void Ritual", popularity = "85.4%" },
            LEGS = { id = 219908, icon = "Interface/ICONS/inv_pants_04", name = "Defender's Armor Kit", popularity = "56.8%" },
            BACK = { id = 223737, icon = "Interface/ICONS/inv_misc_cape_19", name = "Chant of Leeching Fangs", popularity = "84.0%" },
            FEET = { id = 223656, icon = "Interface/ICONS/inv_boots_05", name = "Defender's March", popularity = "72.0%" },
            CHEST = { id = 223692, icon = "Interface/ICONS/inv_chest_chain_03", name = "Crystalline Radiance", popularity = "93.1%" },
            RINGS = { id = 223701, icon = "Interface/ICONS/inv_jewelcrafting_gem_55", name = "Radiant Haste", popularity = "70.6%" },
            WRIST = { id = 223719, icon = "Interface/ICONS/inv_bracer_07", name = "Chant of Armored Leech", popularity = "82.5%" },
            MAIN_HAND = { id = 223705, icon = "Interface/ICONS/inv_sword_39", name = "Authority of Radiant Power", popularity = "65.9%" },
        },
        epic_gems = {
            { id = 213743, icon = "Interface/ICONS/inv_jewelcrafting_gem_50", name = "Culminating Blasphemite", popularity = "64.2%" },
            { id = 213746, icon = "Interface/ICONS/inv_jewelcrafting_gem_51", name = "Elusive Blasphemite", popularity = "24.3%" },
        },
        gems = {
            { id = 213479, icon = "Interface/ICONS/inv_jewelcrafting_gem_13", name = "Deadly Emerald", popularity = "68.4%" },
            { id = 213455, icon = "Interface/ICONS/inv_jewelcrafting_gem_09", name = "Quick Ruby", popularity = "65.9%" },
            { id = 213470, icon = "Interface/ICONS/inv_jewelcrafting_gem_16", name = "Quick Sapphire", popularity = "42.8%" },
            { id = 213485, icon = "Interface/ICONS/inv_jewelcrafting_gem_14", name = "Versatile Emerald", popularity = "41.1%" },
            { id = 213494, icon = "Interface/ICONS/inv_jewelcrafting_gem_12", name = "Quick Onyx", popularity = "32.8%" },
        },
        HEAD = {
            { id = 229235, name = "Enforcer's Backalley Faceshield", popularity = "64.8%" },
            { id = 207121, name = "Hood of Surging Time", popularity = "10.2%" },
            { id = 207206, name = "Greatwolf Outcast's Companions", popularity = "7.5%" },
            { id = 207220, name = "Mask of the Furnace Seraph", popularity = "5.1%" },
            { id = 193400, name = "Crown of Obsidian Secrets", popularity = "3.7%" },
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "41.2%" },
            { id = 193773, name = "Ominous Chromatic Essence", popularity = "18.7%" },
            { id = 194304, name = "Terros's Captive Core", popularity = "13.5%" },
            { id = 193001, name = "Eye of the Rising Flame", popularity = "10.1%" },
            { id = 193676, name = "Chain of the Green Flight", popularity = "6.2%" },
        },
        SHOULDERS = {
            { id = 229233, name = "Enforcer's Backalley Shoulderplates", popularity = "87.6%" },
            { id = 202456, name = "Pauldrons of the Onyx Crucible", popularity = "5.8%" },
            { id = 207207, name = "Greatwolf Outcast's Companions", popularity = "2.7%" },
            { id = 207222, name = "Furnace Seraph's Shoulderplates", popularity = "2.1%" },
            { id = 193712, name = "Spiked Pauldrons of the Barricade", popularity = "1.1%" },
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "31.0%" },
            { id = 202541, name = "Voice of the Silent Star", popularity = "19.4%" },
            { id = 193511, name = "Cloak of Lost Devotion", popularity = "17.2%" },
            { id = 193787, name = "Periwinkle Cloak", popularity = "15.3%" },
            { id = 193763, name = "Fireproof Drape", popularity = "7.1%" },
        },
        CHEST = {
            { id = 229238, name = "Enforcer's Backalley Vestplate", popularity = "73.7%" },
            { id = 207206, name = "Greatwolf Outcast's Companions", popularity = "8.2%" },
            { id = 207218, name = "Furnace Seraph's Chestplate", popularity = "7.6%" },
            { id = 202454, name = "Breastplate of the Onyx Crucible", popularity = "6.1%" },
            { id = 193661, name = "Twisted Vision's Breastplate", popularity = "2.1%" },
        },
        WRISTS = {
            { id = 222435, name = "Everforged Vambraces", popularity = "40.4%" },
            { id = 193714, name = "Venerated Raptorhide Bindings", popularity = "19.2%" },
            { id = 202458, name = "Armplates of the Onyx Crucible", popularity = "15.1%" },
            { id = 207224, name = "Furnace Seraph's Wristguards", popularity = "13.7%" },
            { id = 207208, name = "Greatwolf Outcast's Bindings", popularity = "6.3%" },
        },
        HANDS = {
            { id = 229236, name = "Enforcer's Backalley Crushers", popularity = "85.2%" },
            { id = 202455, name = "Gauntlets of the Onyx Crucible", popularity = "5.9%" },
            { id = 207221, name = "Furnace Seraph's Handguards", popularity = "3.8%" },
            { id = 207207, name = "Greatwolf Outcast's Grips", popularity = "3.1%" },
            { id = 193666, name = "Gauntlets of the Green Guardian", popularity = "1.2%" },
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "91.3%" },
            { id = 207209, name = "Greatwolf Outcast's Belt", popularity = "3.2%" },
            { id = 207225, name = "Furnace Seraph's Waistguard", popularity = "2.8%" },
            { id = 202457, name = "Girdle of the Onyx Crucible", popularity = "1.7%" },
            { id = 193668, name = "Forlorn Leaf Clasp", popularity = "0.7%" },
        },
        LEGS = {
            { id = 229234, name = "Enforcer's Backalley Chausses", popularity = "86.6%" },
            { id = 202453, name = "Legplates of the Onyx Crucible", popularity = "5.7%" },
            { id = 207219, name = "Furnace Seraph's Legplates", popularity = "3.9%" },
            { id = 207210, name = "Greatwolf Outcast's Legguards", popularity = "2.6%" },
            { id = 193669, name = "Legguards of the Green Guardian", popularity = "1.2%" },
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "29.3%" },
            { id = 207211, name = "Greatwolf Outcast's Treads", popularity = "21.1%" },
            { id = 207223, name = "Furnace Seraph's Warboots", popularity = "18.4%" },
            { id = 202459, name = "Sabatons of the Onyx Crucible", popularity = "16.2%" },
            { id = 193670, name = "Boots of the Green Guardian", popularity = "7.3%" },
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "35.0%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "34.2%" },
            { id = 193000, name = "Seal of Filial Duty", popularity = "13.7%" },
            { id = 192999, name = "Signet of Titanic Insight", popularity = "9.1%" },
            { id = 193708, name = "Circle of Ascended Frost", popularity = "8.0%" },
        },
        FINGER2 = {
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "34.2%" },
            { id = 231265, name = "The Jastor Diamond", popularity = "35.0%" },
            { id = 193000, name = "Seal of Filial Duty", popularity = "13.7%" },
            { id = 192999, name = "Signet of Titanic Insight", popularity = "9.1%" },
            { id = 193708, name = "Circle of Ascended Frost", popularity = "8.0%" },
        },
        MAIN_HAND = {
            { id = 222440, name = "Everforged Longsword", popularity = "32.7%" },
            { id = 228895, name = "Remixed Ignition Saber", popularity = "12.5%" },
            { id = 169608, name = "Tearing Sawtooth Blade", popularity = "9.7%" },
            { id = 221096, name = "Rail Rider's Bisector", popularity = "8.6%" },
            { id = 222451, name = "Charged Slicer", popularity = "6.0%" },
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "40.3%" },
            { id = 222873, name = "Duskthread Lining", popularity = "14.5%" },
            { id = 222870, name = "Dawnthread Lining", popularity = "5.8%" },
            { id = 219504, name = "Writhing Armor Banding", popularity = "7.4%" },
            { id = 226024, name = "Darkmoon Sigil: Ascension", popularity = "7.4%" },
        },
        TRINKET1 = {
            { id = 219309, name = "Tome of Light's Devotion", popularity = "23.3%" },
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "23.3%" },
            { id = 193773, name = "Ominous Chromatic Essence", popularity = "18.1%" },
            { id = 194302, name = "Storm-Eater's Boon", popularity = "12.7%" },
            { id = 202612, name = "Beacon to the Beyond", popularity = "10.2%" },
        },
        TRINKET2 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "23.3%" },
            { id = 219309, name = "Tome of Light's Devotion", popularity = "23.3%" },
            { id = 193773, name = "Ominous Chromatic Essence", popularity = "18.1%" },
            { id = 194302, name = "Storm-Eater's Boon", popularity = "12.7%" },
            { id = 202612, name = "Beacon to the Beyond", popularity = "10.2%" },
        },
        consumables = {
            { id = 212283, icon = "Interface/ICONS/inv_potion_purlple", name = "Flask of Alchemical Chaos", type = "Flask", popularity = "29.8%" },
            { id = 211880, icon = "Interface/ICONS/inv_flask_red", name = "Algari Healing Potion", type = "Health Potion", popularity = "66.0%" },
            { id = 212265, icon = "Interface/ICONS/trade_alchemy_potiona4", name = "Tempered Potion", type = "Combat Potion", popularity = "73.7%" },
            { id = 222720, icon = "Interface/ICONS/spell_misc_food", name = "The Sushi Special", type = "Food Buff", popularity = "33.1%" },
            { id = 224107, icon = "Interface/ICONS/inv_blacksmithing_modifiedcraftingreagent_blue", name = "Algari Mana Oil", type = "Weapon Buff", popularity = "86.8%" },
        },
    },
    ARMS = {
        icon = "Interface/ICONS/Ability_Warrior_SavageBlow",
        talent = "",
        statprio = "",
        {},
    },
    FURY = {
        icon = "Interface/ICONS/Ability_Warrior_InnerRage",
        talent = "",
        statprio = "",
        {},
    },
} 