-- Auto-generated by scraper
WishListData_Evoker = {
    DEVASTATION = {
        icon = "Interface/ICONS/Invoker_Spec_DragonRed",
        talent = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGzYmxsMzYmBzMGDTYmpZ2GLDGGjZWmBgZ2GzMLzMDmBmxMwCYDMDTgFwywM",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "69.7%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "76.2%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "54.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "66.8%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "82.8%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "51.3%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "43.7%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "47.8%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "67.4%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "5.7%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.1%" }
        },
        gems = {
            { id = 213455, name = "Quick Ruby", popularity = "63.3%" },
            { id = 213479, name = "Deadly Emerald", popularity = "60.8%" },
            { id = 213494, name = "Quick Onyx", popularity = "23.0%" },
            { id = 213491, name = "Deadly Onyx", popularity = "20.6%" },
            { id = 213470, name = "Quick Sapphire", popularity = "17.9%" }
        },
        HEAD = {
            { id = 229280, name = "Opulent Treasurescale's Crowned Jewel", popularity = "59.4%" },
            { id = 228859, name = "BiSSanitized Scraphood", popularity = "13.8%" },
            { id = 235223, name = "Psychogenic Prognosticator's Lenses", popularity = "8.1%" },
            { id = 219337, name = "Glyph-Etched Guise", popularity = "6.1%" },
            { id = 178799, name = "Amphitheater Stalker's Hood", popularity = "3.1%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "40.2%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "21.2%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "16.3%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "7.2%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "2.1%" }
        },
        SHOULDERS = {
            { id = 229278, name = "BiSOpulent Treasurescale's Gleaming Mantle", popularity = "88.1%" },
            { id = 228860, name = "Epaulettes of Failed Enforcers", popularity = "1.5%" },
            { id = 234503, name = "Skystreak's Hidden Missiles", popularity = "1.4%" },
            { id = 212027, name = "Fumaroles of the Destroyer", popularity = "0.9%" },
            { id = 219338, name = "Glyph-Etched Epaulets", popularity = "0.9%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "48.9%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "9.2%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "8.1%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "7.7%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "5.3%" }
        },
        CHEST = {
            { id = 229283, name = "BiSOpulent Treasurescale's Tunic", popularity = "84.1%" },
            { id = 228852, name = "Blazer of Glory", popularity = "3.2%" },
            { id = 178794, name = "Triumphant Combatant's Chainmail", popularity = "2.4%" },
            { id = 219336, name = "Glyph-Etched Breastplate", popularity = "1.2%" },
            { id = 221041, name = "Boltbreaker Armor", popularity = "1.2%" }
        },
        WRISTS = {
            { id = 219342, name = "BiSGlyph-Etched Vambraces", popularity = "63.9%" },
            { id = 221124, name = "Consecrated Baron's Bindings", popularity = "5.0%" },
            { id = 228878, name = "Made Manacles", popularity = "4.6%" },
            { id = 221059, name = "I'pa's Pale Aleguards", popularity = "4.2%" },
            { id = 228846, name = "Galvanic Graffiti Cuffs", popularity = "4.1%" }
        },
        HANDS = {
            { id = 229281, name = "BiSOpulent Treasurescale's Gold-Counters", popularity = "83.2%" },
            { id = 219341, name = "Glyph-Etched Gauntlets", popularity = "3.1%" },
            { id = 178798, name = "Grips of Overwhelming Beatings", popularity = "2.5%" },
            { id = 159357, name = "Linked Pummeler Grips", popularity = "1.6%" },
            { id = 168971, name = "Swift Pneumatic Grips", popularity = "1.6%" }
        },
        WAIST = {
            { id = 245965, name = "BiSDurable Information Securing Container", popularity = "92.2%" },
            { id = 234501, name = "Portable Power Generator", popularity = "0.9%" },
            { id = 219339, name = "Glyph-Etched Binding", popularity = "0.8%" },
            { id = 159361, name = "Shalebiter Interlinked Chain", popularity = "0.6%" },
            { id = 168983, name = "Maniacal Monarch's Girdle", popularity = "0.5%" }
        },
        LEGS = {
            { id = 229279, name = "BiSOpulent Treasurescale's Petticoat", popularity = "90.0%" },
            { id = 221065, name = "Pollen-Lugger Treads", popularity = "1.4%" },
            { id = 219340, name = "Glyph-Etched Cuisses", popularity = "1.1%" },
            { id = 158341, name = "Chemical Blaster's Legguards", popularity = "0.8%" },
            { id = 212028, name = "Legguards of the Destroyer", popularity = "0.8%" }
        },
        FEET = {
            { id = 228862, name = "BiSShrapnel-Ridden Sabatons", popularity = "21.0%" },
            { id = 219335, name = "Glyph-Etched Stompers", popularity = "19.5%" },
            { id = 229282, name = "Opulent Treasurescale's Boots", popularity = "16.5%" },
            { id = 178796, name = "Boots of Shuddering Matter", popularity = "11.4%" },
            { id = 221035, name = "Treads of the Galvanic Skysoarer", popularity = "8.3%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "49.9%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "34.6%" },
            { id = 178871, name = "BiSBloodoath Signet", popularity = "22.3%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "21.1%" },
            { id = 228840, name = "Faded Championship Ring", popularity = "12.1%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "37.7%" },
            { id = 232805, name = "BiSBest-in-Slots", popularity = "24.7%" },
            { id = 222450, name = "Charged Invoker", popularity = "5.8%" },
            { id = 231268, name = "Blastfurious Machete", popularity = "5.1%" },
            { id = 221032, name = "Voltaic Stormcaller", popularity = "5.1%" }
        },
        OFF_HAND = {
            { id = 222566, name = "Vagabond's Torch", popularity = "7.9%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "2.8%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "2.0%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "1.5%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "1.1%" }
        },
        TRINKET1 = {
            { id = 230192, name = "BiSMug's Moxie Jug", popularity = "61.0%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "54.7%" },
            { id = 219308, name = "Signet of the Priory", popularity = "25.5%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "16.8%" },
            { id = 219296, name = "Entropic Skardyn Core", popularity = "6.8%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "54.2%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "50.5%" },
            { id = 212265, name = "Tempered Potion", popularity = "50.1%" },
            { id = 222720, name = "The Sushi Special", popularity = "27.6%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "77.3%" }
        }
    },
    PRESERVATION = {
        icon = "Interface/ICONS/Invoker_Spec_DragonGreen",
        talent = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZ2mlBGzMjZxMzYAAAwMDjZMGmJGzAAAAmZmJjtZmZ2GzAAwY2swCMwMM0gxCMA",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "55.9%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "46.6%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "39.6%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "58.4%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "69.8%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "39.5%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "37.0%" },
            MAINHAND = { id = 223778, name = "Authority of Fiery Resolve", popularity = "41.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "40.5%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "23.3%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "5.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "36.8%" },
            { id = 213491, name = "Deadly Onyx", popularity = "35.9%" },
            { id = 213482, name = "Masterful Emerald", popularity = "33.7%" },
            { id = 213455, name = "Quick Ruby", popularity = "32.5%" },
            { id = 213494, name = "Quick Onyx", popularity = "26.4%" }
        },
        HEAD = {
            { id = 229280, name = "Opulent Treasurescale's Crowned Jewel", popularity = "76.5%" },
            { id = 235223, name = "Psychogenic Prognosticator's Lenses", popularity = "4.2%" },
            { id = 228859, name = "Sanitized Scraphood", popularity = "3.8%" },
            { id = 219337, name = "Glyph-Etched Guise", popularity = "2.8%" },
            { id = 212029, name = "Horns of the Destroyer", popularity = "2.0%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "33.2%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "23.9%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "10.9%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "7.7%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "6.3%" }
        },
        SHOULDERS = {
            { id = 229278, name = "Opulent Treasurescale's Gleaming Mantle", popularity = "84.7%" },
            { id = 212027, name = "Fumaroles of the Destroyer", popularity = "2.6%" },
            { id = 234503, name = "Skystreak's Hidden Missiles", popularity = "1.9%" },
            { id = 219338, name = "Glyph-Etched Epaulets", popularity = "1.2%" },
            { id = 235416, name = "Crashguard Spaulders", popularity = "1.1%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "28.7%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "15.8%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "9.7%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "8.7%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "7.1%" }
        },
        CHEST = {
            { id = 229283, name = "Opulent Treasurescale's Tunic", popularity = "81.1%" },
            { id = 228852, name = "Blazer of Glory", popularity = "3.5%" },
            { id = 234502, name = "Bront's Singed Blastcoat", popularity = "2.4%" },
            { id = 221041, name = "Boltbreaker Armor", popularity = "2.3%" },
            { id = 178794, name = "Triumphant Combatant's Chainmail", popularity = "1.9%" }
        },
        WRISTS = {
            { id = 219342, name = "Glyph-Etched Vambraces", popularity = "43.8%" },
            { id = 221124, name = "Consecrated Baron's Bindings", popularity = "10.2%" },
            { id = 228846, name = "Galvanic Graffiti Cuffs", popularity = "9.0%" },
            { id = 158357, name = "Bindings of Enraged Earth", popularity = "6.5%" },
            { id = 228878, name = "Made Manacles", popularity = "6.1%" }
        },
        HANDS = {
            { id = 229281, name = "Opulent Treasurescale's Gold-Counters", popularity = "75.9%" },
            { id = 168971, name = "Swift Pneumatic Grips", popularity = "3.6%" },
            { id = 178798, name = "Grips of Overwhelming Beatings", popularity = "3.4%" },
            { id = 219341, name = "Glyph-Etched Gauntlets", popularity = "2.9%" },
            { id = 228867, name = "Gravi-Gunk Handlers", popularity = "2.5%" }
        },
        WAIST = {
            { id = 245965, name = "Durable Information Securing Container", popularity = "90.2%" },
            { id = 234501, name = "Portable Power Generator", popularity = "1.5%" },
            { id = 219339, name = "Glyph-Etched Binding", popularity = "1.2%" },
            { id = 168983, name = "Maniacal Monarch's Girdle", popularity = "0.8%" },
            { id = 159361, name = "Shalebiter Interlinked Chain", popularity = "0.8%" }
        },
        LEGS = {
            { id = 229279, name = "Opulent Treasurescale's Petticoat", popularity = "83.0%" },
            { id = 212028, name = "Legguards of the Destroyer", popularity = "2.3%" },
            { id = 158341, name = "Chemical Blaster's Legguards", popularity = "2.3%" },
            { id = 219340, name = "Glyph-Etched Cuisses", popularity = "1.9%" },
            { id = 221065, name = "Pollen-Lugger Treads", popularity = "1.6%" }
        },
        FEET = {
            { id = 219335, name = "Glyph-Etched Stompers", popularity = "16.8%" },
            { id = 228862, name = "Shrapnel-Ridden Sabatons", popularity = "15.1%" },
            { id = 221035, name = "Treads of the Galvanic Skysoarer", popularity = "14.2%" },
            { id = 229282, name = "Opulent Treasurescale's Boots", popularity = "9.2%" },
            { id = 178796, name = "Boots of Shuddering Matter", popularity = "9.2%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "46.6%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "39.6%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "21.3%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "11.3%" },
            { id = 221198, name = "85-Year Tenure Ring", popularity = "9.6%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "45.1%" },
            { id = 232805, name = "Best-in-Slots", popularity = "6.1%" },
            { id = 231268, name = "Blastfurious Machete", popularity = "5.9%" },
            { id = 221105, name = "Dark Zone Headtaker", popularity = "3.9%" },
            { id = 178789, name = "Fleshcrafter's Knife", popularity = "3.7%" }
        },
        OFF_HAND = {
            { id = 222566, name = "Vagabond's Torch", popularity = "14.2%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "5.1%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "3.5%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "3.1%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "1.8%" }
        },
        TRINKET1 = {
            { id = 230186, name = "Mister Pick-Me-Up", popularity = "66.4%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "26.9%" },
            { id = 230192, name = "Mug's Moxie Jug", popularity = "18.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "13.5%" },
            { id = 230027, name = "House of Cards", popularity = "11.7%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "25.1%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "27.6%" },
            { id = 212265, name = "Tempered Potion", popularity = "7.0%" },
            { id = 222720, name = "The Sushi Special", popularity = "14.3%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "67.9%" }
        }
    },
    AUGMENTATION = {
        icon = "Interface/ICONS/Invoker_Spec_DragonBronze",
        talent = "CEcBAAAAAAAAAAAAAAAAAAAAAwMLjtZmZGLDMzyMGzYmNAAAAAAAAMzADjxUDzMDAAAAMzMbjZGjZGDzwYwCsMGGLDgZQshZmB",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "37.0%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "73.1%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "50.6%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "63.6%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "80.5%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "55.7%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "49.6%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "68.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "60.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "10.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "60.4%" },
            { id = 213455, name = "Quick Ruby", popularity = "50.0%" },
            { id = 213494, name = "Quick Onyx", popularity = "30.5%" },
            { id = 213482, name = "Masterful Emerald", popularity = "20.8%" },
            { id = 213491, name = "Deadly Onyx", popularity = "16.6%" }
        },
        HEAD = {
            { id = 229280, name = "Opulent Treasurescale's Crowned Jewel", popularity = "70.6%" },
            { id = 228859, name = "BiSSanitized Scraphood", popularity = "7.5%" },
            { id = 219337, name = "Glyph-Etched Guise", popularity = "4.8%" },
            { id = 235223, name = "Psychogenic Prognosticator's Lenses", popularity = "4.1%" },
            { id = 212029, name = "Horns of the Destroyer", popularity = "1.6%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "40.4%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "18.3%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "15.9%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "4.7%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "4.1%" }
        },
        SHOULDERS = {
            { id = 229278, name = "BiSOpulent Treasurescale's Gleaming Mantle", popularity = "86.5%" },
            { id = 212027, name = "Fumaroles of the Destroyer", popularity = "2.2%" },
            { id = 219338, name = "Glyph-Etched Epaulets", popularity = "1.4%" },
            { id = 228860, name = "Epaulettes of Failed Enforcers", popularity = "1.2%" },
            { id = 234503, name = "Skystreak's Hidden Missiles", popularity = "1.2%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "38.2%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "12.8%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "12.6%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "6.3%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "5.4%" }
        },
        CHEST = {
            { id = 229283, name = "BiSOpulent Treasurescale's Tunic", popularity = "81.4%" },
            { id = 228852, name = "Blazer of Glory", popularity = "3.3%" },
            { id = 219336, name = "Glyph-Etched Breastplate", popularity = "2.6%" },
            { id = 212032, name = "Scales of the Destroyer", popularity = "1.8%" },
            { id = 178794, name = "Triumphant Combatant's Chainmail", popularity = "1.7%" }
        },
        WRISTS = {
            { id = 219342, name = "BiSGlyph-Etched Vambraces", popularity = "52.8%" },
            { id = 221124, name = "Consecrated Baron's Bindings", popularity = "10.0%" },
            { id = 228846, name = "Galvanic Graffiti Cuffs", popularity = "6.0%" },
            { id = 228878, name = "Made Manacles", popularity = "4.6%" },
            { id = 211028, name = "Torchbearer's Bracers", popularity = "3.9%" }
        },
        HANDS = {
            { id = 229281, name = "BiSOpulent Treasurescale's Gold-Counters", popularity = "71.7%" },
            { id = 178798, name = "Grips of Overwhelming Beatings", popularity = "5.0%" },
            { id = 168971, name = "Swift Pneumatic Grips", popularity = "4.3%" },
            { id = 219341, name = "Glyph-Etched Gauntlets", popularity = "3.6%" },
            { id = 212030, name = "Rippers of the Destroyer", popularity = "2.4%" }
        },
        WAIST = {
            { id = 245965, name = "BiSDurable Information Securing Container", popularity = "91.8%" },
            { id = 219339, name = "Glyph-Etched Binding", popularity = "1.3%" },
            { id = 229277, name = "Opulent Treasurescale's Radiant Chain", popularity = "1.2%" },
            { id = 234501, name = "Portable Power Generator", popularity = "1.1%" },
            { id = 168983, name = "Maniacal Monarch's Girdle", popularity = "0.3%" }
        },
        LEGS = {
            { id = 229279, name = "BiSOpulent Treasurescale's Petticoat", popularity = "89.2%" },
            { id = 219340, name = "Glyph-Etched Cuisses", popularity = "1.8%" },
            { id = 212028, name = "Legguards of the Destroyer", popularity = "1.5%" },
            { id = 158341, name = "Chemical Blaster's Legguards", popularity = "0.9%" },
            { id = 211025, name = "Torchbearer's Greaves", popularity = "0.9%" }
        },
        FEET = {
            { id = 219335, name = "Glyph-Etched Stompers", popularity = "27.0%" },
            { id = 228862, name = "Shrapnel-Ridden Sabatons", popularity = "16.6%" },
            { id = 178796, name = "Boots of Shuddering Matter", popularity = "12.2%" },
            { id = 229282, name = "BiSOpulent Treasurescale's Boots", popularity = "11.2%" },
            { id = 221035, name = "Treads of the Galvanic Skysoarer", popularity = "6.6%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "45.4%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "31.0%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "27.2%" },
            { id = 178871, name = "BiSBloodoath Signet", popularity = "19.0%" },
            { id = 228840, name = "Faded Championship Ring", popularity = "11.0%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "40.8%" },
            { id = 232805, name = "BiSBest-in-Slots", popularity = "16.7%" },
            { id = 231268, name = "Blastfurious Machete", popularity = "6.6%" },
            { id = 221032, name = "Voltaic Stormcaller", popularity = "6.0%" },
            { id = 222450, name = "Charged Invoker", popularity = "4.1%" }
        },
        OFF_HAND = {
            { id = 222566, name = "Vagabond's Torch", popularity = "7.0%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "4.6%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "2.3%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "2.0%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "1.2%" }
        },
        TRINKET1 = {
            { id = 230192, name = "BiSMug's Moxie Jug", popularity = "62.2%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "27.5%" },
            { id = 230027, name = "House of Cards", popularity = "16.4%" },
            { id = 219308, name = "Signet of the Priory", popularity = "15.7%" },
            { id = 219296, name = "Entropic Skardyn Core", popularity = "12.7%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "33.5%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "45.9%" },
            { id = 212265, name = "Tempered Potion", popularity = "36.3%" },
            { id = 222720, name = "The Sushi Special", popularity = "25.5%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "74.0%" }
        }
    }
}
