-- Auto-generated by scraper
WishListData_Warlock = {
    AFFLICTION = {
        icon = "Interface/ICONS/Spell_Shadow_DeathCoil",
        talent = "CkQAAAAAAAAAAAAAAAAAAAAAAAzMzMzMjYWMMmNzMDz2AAAAmZMzyMjxyMzMLmxMDAYGLwAziRjZAMLglZAAAAAAAAwMsA",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "67.1%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "79.8%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "49.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "58.8%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "83.9%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "45.6%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "45.8%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "54.8%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "65.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "8.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213482, name = "Masterful Emerald", popularity = "56.6%" },
            { id = 213494, name = "Quick Onyx", popularity = "34.8%" },
            { id = 213455, name = "Quick Ruby", popularity = "31.6%" },
            { id = 213479, name = "Deadly Emerald", popularity = "31.2%" },
            { id = 213458, name = "Masterful Ruby", popularity = "30.5%" }
        },
        HEAD = {
            { id = 229325, name = "BiSSpliced Fiendtrader's Transcendence", popularity = "88.7%" },
            { id = 222818, name = "Consecrated Hood", popularity = "1.8%" },
            { id = 221055, name = "Cinderbrew-Soaked Cowl", popularity = "0.8%" },
            { id = 228871, name = "Cleanup Crew's Wastemask", popularity = "0.8%" },
            { id = 224590, name = "Deep-Dweller's Cowl", popularity = "0.8%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "37.1%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "26.4%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "14.4%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "5.3%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "4.7%" }
        },
        SHOULDERS = {
            { id = 229323, name = "BiSSpliced Fiendtrader's Loyal Servants", popularity = "90.9%" },
            { id = 235812, name = "Shoulderguards of Fraying Sanity", popularity = "1.4%" },
            { id = 211039, name = "Cave Topographer's Shoulders", popularity = "0.6%" },
            { id = 235418, name = "Exquisitely Aerodynamic Shoulderpads", popularity = "0.6%" },
            { id = 212072, name = "Hexflame Coven's Altar", popularity = "0.4%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "27.5%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "15.8%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "12.4%" },
            { id = 228839, name = "BiSUndercircuit Racing Flag", popularity = "10.9%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "9.1%" }
        },
        CHEST = {
            { id = 229328, name = "BiSSpliced Fiendtrader's Surgical Gown", popularity = "90.6%" },
            { id = 222819, name = "Consecrated Robe", popularity = "1.3%" },
            { id = 178792, name = "Soulsewn Vestments", popularity = "0.8%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "0.8%" },
            { id = 228850, name = "Bottom-Dollar Blouse", popularity = "0.7%" }
        },
        WRISTS = {
            { id = 222815, name = "Consecrated Cuffs", popularity = "51.7%" },
            { id = 228857, name = "BiSUnderparty Admission Bracelet", popularity = "10.9%" },
            { id = 221104, name = "Gleamwax Shackles", popularity = "7.7%" },
            { id = 228881, name = "Illicit Bankroll Bracers", popularity = "4.6%" },
            { id = 221037, name = "Charged Rookfeather Wraps", popularity = "4.1%" }
        },
        HANDS = {
            { id = 229326, name = "Spliced Fiendtrader's Demonic Grasp", popularity = "55.4%" },
            { id = 222822, name = "Consecrated Gloves", popularity = "10.5%" },
            { id = 221067, name = "Punctured Apiary Gloves", popularity = "9.8%" },
            { id = 221108, name = "King's Malicious Clutches", popularity = "8.3%" },
            { id = 228872, name = "BiSGolden Handshakers", popularity = "5.2%" }
        },
        WAIST = {
            { id = 242664, name = "BiSDurable Information Securing Container", popularity = "92.8%" },
            { id = 222816, name = "Consecrated Cord", popularity = "1.0%" },
            { id = 229322, name = "Spliced Fiendtrader's Sash", popularity = "0.9%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "0.6%" },
            { id = 159226, name = "Excavator's Safety Belt", popularity = "0.3%" }
        },
        LEGS = {
            { id = 229324, name = "BiSSpliced Fiendtrader's Skin Tights", popularity = "85.3%" },
            { id = 222820, name = "Consecrated Leggings", popularity = "2.2%" },
            { id = 228865, name = "Pit Doctor's Petticoat", popularity = "2.1%" },
            { id = 221050, name = "Ancient Hardened Legwraps", popularity = "1.7%" },
            { id = 158350, name = "Rowdy Reveler's Legwraps", popularity = "1.6%" }
        },
        FEET = {
            { id = 222814, name = "BiSConsecrated Slippers", popularity = "34.7%" },
            { id = 229327, name = "Spliced Fiendtrader's Soles", popularity = "14.0%" },
            { id = 168964, name = "Hyperthread Boots", popularity = "9.4%" },
            { id = 159235, name = "Deranged Alchemist's Slippers", popularity = "9.2%" },
            { id = 221043, name = "Cloudstrider Soles", popularity = "7.4%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "72.8%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "23.2%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "21.0%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "14.8%" },
            { id = 221197, name = "Hoop of the Blighted", popularity = "9.9%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "30.2%" },
            { id = 231268, name = "Blastfurious Machete", popularity = "20.0%" },
            { id = 228896, name = "BiSStix's Metal Detector", popularity = "9.5%" },
            { id = 221062, name = "Scalding Queenmaker's Shiv", popularity = "6.7%" },
            { id = 222444, name = "Charged Hexsword", popularity = "6.4%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "39.1%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "5.7%" },
            { id = 228906, name = "Operator's Fraud Detector", popularity = "2.7%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "1.3%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "1.2%" }
        },
        TRINKET1 = {
            { id = 230192, name = "Mug's Moxie Jug", popularity = "76.5%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "49.9%" },
            { id = 219308, name = "Signet of the Priory", popularity = "32.1%" },
            { id = 219296, name = "Entropic Skardyn Core", popularity = "7.1%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "4.7%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "56.1%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "38.1%" },
            { id = 212265, name = "Tempered Potion", popularity = "56.8%" },
            { id = 222720, name = "The Sushi Special", popularity = "15.8%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "79.7%" }
        }
    },
    DEMONOLOGY = {
        icon = "Interface/ICONS/Spell_Shadow_Metamorphosis",
        talent = "CoQAAAAAAAAAAAAAAAAAAAAAAAmZmZmZEzi5BMmtZmZY2GAAAAAAAAAADwYGDLwALDL0wCzMmZ2GzsZmZmZMmZGMmZGDmBAAA",
        statprio = "Haste > Mastery > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "70.0%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "79.2%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "51.5%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "58.0%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "84.4%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "58.2%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "50.7%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "66.8%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "67.1%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "7.8%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213482, name = "Masterful Emerald", popularity = "46.3%" },
            { id = 213479, name = "Deadly Emerald", popularity = "44.3%" },
            { id = 213455, name = "Quick Ruby", popularity = "35.0%" },
            { id = 213494, name = "Quick Onyx", popularity = "30.5%" },
            { id = 213458, name = "Masterful Ruby", popularity = "21.5%" }
        },
        HEAD = {
            { id = 229325, name = "BiSSpliced Fiendtrader's Transcendence", popularity = "90.5%" },
            { id = 222818, name = "Consecrated Hood", popularity = "1.6%" },
            { id = 235226, name = "Inventor's Ingenious Trifocals", popularity = "1.4%" },
            { id = 228871, name = "Cleanup Crew's Wastemask", popularity = "0.5%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "0.5%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "37.6%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "27.1%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "14.1%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "5.9%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "2.4%" }
        },
        SHOULDERS = {
            { id = 229323, name = "BiSSpliced Fiendtrader's Loyal Servants", popularity = "89.6%" },
            { id = 235812, name = "Shoulderguards of Fraying Sanity", popularity = "1.2%" },
            { id = 235418, name = "Exquisitely Aerodynamic Shoulderpads", popularity = "0.9%" },
            { id = 228870, name = "Underboss's Tailored Mantle", popularity = "0.9%" },
            { id = 221072, name = "Moneymaking Businessmantle", popularity = "0.8%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "28.5%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "15.1%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "10.9%" },
            { id = 228839, name = "BiSUndercircuit Racing Flag", popularity = "9.4%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "8.6%" }
        },
        CHEST = {
            { id = 229328, name = "BiSSpliced Fiendtrader's Surgical Gown", popularity = "91.6%" },
            { id = 222819, name = "Consecrated Robe", popularity = "1.1%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "1.0%" },
            { id = 235420, name = "Petticoat of the Self-Stylized Azerite Baron", popularity = "0.5%" },
            { id = 212077, name = "Hexflame Coven's Ritual Harness", popularity = "0.5%" }
        },
        WRISTS = {
            { id = 222815, name = "Consecrated Cuffs", popularity = "46.2%" },
            { id = 228857, name = "BiSUnderparty Admission Bracelet", popularity = "9.5%" },
            { id = 221104, name = "Gleamwax Shackles", popularity = "6.7%" },
            { id = 159240, name = "Rixxa's Sweat-Wicking Cuffs", popularity = "5.8%" },
            { id = 228881, name = "Illicit Bankroll Bracers", popularity = "5.7%" }
        },
        HANDS = {
            { id = 229326, name = "Spliced Fiendtrader's Demonic Grasp", popularity = "59.2%" },
            { id = 222822, name = "Consecrated Gloves", popularity = "8.3%" },
            { id = 221108, name = "King's Malicious Clutches", popularity = "8.2%" },
            { id = 221067, name = "Punctured Apiary Gloves", popularity = "8.2%" },
            { id = 228872, name = "BiSGolden Handshakers", popularity = "3.5%" }
        },
        WAIST = {
            { id = 242664, name = "BiSDurable Information Securing Container", popularity = "91.2%" },
            { id = 222816, name = "Consecrated Cord", popularity = "1.2%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "0.9%" },
            { id = 168958, name = "Ringmaster's Cummerbund", popularity = "0.6%" },
            { id = 229322, name = "Spliced Fiendtrader's Sash", popularity = "0.6%" }
        },
        LEGS = {
            { id = 229324, name = "BiSSpliced Fiendtrader's Skin Tights", popularity = "83.6%" },
            { id = 228865, name = "Pit Doctor's Petticoat", popularity = "2.7%" },
            { id = 221050, name = "Ancient Hardened Legwraps", popularity = "2.4%" },
            { id = 158350, name = "Rowdy Reveler's Legwraps", popularity = "2.2%" },
            { id = 222820, name = "Consecrated Leggings", popularity = "2.0%" }
        },
        FEET = {
            { id = 222814, name = "BiSConsecrated Slippers", popularity = "33.7%" },
            { id = 229327, name = "Spliced Fiendtrader's Soles", popularity = "14.4%" },
            { id = 168964, name = "Hyperthread Boots", popularity = "10.9%" },
            { id = 221043, name = "Cloudstrider Soles", popularity = "10.0%" },
            { id = 159235, name = "Deranged Alchemist's Slippers", popularity = "7.4%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "65.8%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "27.1%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "19.4%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "13.2%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "13.1%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "33.9%" },
            { id = 231268, name = "Blastfurious Machete", popularity = "18.9%" },
            { id = 228896, name = "BiSStix's Metal Detector", popularity = "6.8%" },
            { id = 221062, name = "Scalding Queenmaker's Shiv", popularity = "6.6%" },
            { id = 222444, name = "Charged Hexsword", popularity = "6.3%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "35.1%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "5.4%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "2.5%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "2.2%" },
            { id = 228906, name = "Operator's Fraud Detector", popularity = "2.1%" }
        },
        TRINKET1 = {
            { id = 230192, name = "Mug's Moxie Jug", popularity = "68.9%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "52.4%" },
            { id = 219308, name = "Signet of the Priory", popularity = "27.1%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "13.9%" },
            { id = 219296, name = "Entropic Skardyn Core", popularity = "7.4%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "47.1%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "40.7%" },
            { id = 212265, name = "Tempered Potion", popularity = "53.5%" },
            { id = 222720, name = "The Sushi Special", popularity = "22.4%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "76.2%" }
        }
    },
    DESTRUCTION = {
        icon = "Interface/ICONS/Spell_Shadow_RainOfFire",
        talent = "CsQAAAAAAAAAAAAAAAAAAAAAAAmZmZmZEziZMmNzMDzysZMmxsY2MLLzMDAAAAMMz2yMzywCMwsY0YGAzG2wAAAAAAAYGjZAA",
        statprio = "Haste > Mastery > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "65.4%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "76.3%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "49.7%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "55.7%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "80.9%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "53.2%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "49.3%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "58.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "65.0%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "5.8%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.3%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "47.5%" },
            { id = 213455, name = "Quick Ruby", popularity = "40.4%" },
            { id = 213482, name = "Masterful Emerald", popularity = "39.2%" },
            { id = 213494, name = "Quick Onyx", popularity = "28.3%" },
            { id = 213458, name = "Masterful Ruby", popularity = "23.6%" }
        },
        HEAD = {
            { id = 229325, name = "BiSSpliced Fiendtrader's Transcendence", popularity = "87.9%" },
            { id = 235226, name = "Inventor's Ingenious Trifocals", popularity = "1.6%" },
            { id = 222818, name = "Consecrated Hood", popularity = "1.2%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "0.9%" },
            { id = 228871, name = "Cleanup Crew's Wastemask", popularity = "0.8%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "34.5%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "24.3%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "16.9%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "4.9%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "3.8%" }
        },
        SHOULDERS = {
            { id = 229323, name = "BiSSpliced Fiendtrader's Loyal Servants", popularity = "86.0%" },
            { id = 235812, name = "Shoulderguards of Fraying Sanity", popularity = "1.6%" },
            { id = 235418, name = "Exquisitely Aerodynamic Shoulderpads", popularity = "1.2%" },
            { id = 228870, name = "Underboss's Tailored Mantle", popularity = "1.1%" },
            { id = 222821, name = "Consecrated Mantle", popularity = "1.1%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "29.5%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "14.5%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "11.5%" },
            { id = 228839, name = "BiSUndercircuit Racing Flag", popularity = "9.8%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "8.8%" }
        },
        CHEST = {
            { id = 229328, name = "BiSSpliced Fiendtrader's Surgical Gown", popularity = "90.2%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "1.0%" },
            { id = 222819, name = "Consecrated Robe", popularity = "0.7%" },
            { id = 212077, name = "Hexflame Coven's Ritual Harness", popularity = "0.6%" },
            { id = 228850, name = "Bottom-Dollar Blouse", popularity = "0.5%" }
        },
        WRISTS = {
            { id = 222815, name = "Consecrated Cuffs", popularity = "47.2%" },
            { id = 228857, name = "BiSUnderparty Admission Bracelet", popularity = "11.9%" },
            { id = 221104, name = "Gleamwax Shackles", popularity = "6.6%" },
            { id = 228881, name = "Illicit Bankroll Bracers", popularity = "4.9%" },
            { id = 221037, name = "Charged Rookfeather Wraps", popularity = "4.7%" }
        },
        HANDS = {
            { id = 229326, name = "Spliced Fiendtrader's Demonic Grasp", popularity = "51.9%" },
            { id = 222822, name = "Consecrated Gloves", popularity = "10.8%" },
            { id = 221108, name = "King's Malicious Clutches", popularity = "8.8%" },
            { id = 221067, name = "Punctured Apiary Gloves", popularity = "8.6%" },
            { id = 228872, name = "BiSGolden Handshakers", popularity = "5.6%" }
        },
        WAIST = {
            { id = 242664, name = "BiSDurable Information Securing Container", popularity = "90.6%" },
            { id = 222816, name = "Consecrated Cord", popularity = "1.1%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "0.9%" },
            { id = 229322, name = "Spliced Fiendtrader's Sash", popularity = "0.8%" },
            { id = 228882, name = "Refiner's Conveyor Belt", popularity = "0.5%" }
        },
        LEGS = {
            { id = 229324, name = "BiSSpliced Fiendtrader's Skin Tights", popularity = "84.6%" },
            { id = 228865, name = "Pit Doctor's Petticoat", popularity = "2.3%" },
            { id = 221050, name = "Ancient Hardened Legwraps", popularity = "2.0%" },
            { id = 158350, name = "Rowdy Reveler's Legwraps", popularity = "1.9%" },
            { id = 222820, name = "Consecrated Leggings", popularity = "1.1%" }
        },
        FEET = {
            { id = 222814, name = "BiSConsecrated Slippers", popularity = "29.9%" },
            { id = 229327, name = "Spliced Fiendtrader's Soles", popularity = "18.2%" },
            { id = 221043, name = "Cloudstrider Soles", popularity = "10.3%" },
            { id = 168964, name = "Hyperthread Boots", popularity = "9.9%" },
            { id = 159235, name = "Deranged Alchemist's Slippers", popularity = "7.4%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "65.3%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "23.5%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "21.6%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "13.1%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "11.6%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "34.2%" },
            { id = 231268, name = "Blastfurious Machete", popularity = "20.3%" },
            { id = 228896, name = "BiSStix's Metal Detector", popularity = "6.6%" },
            { id = 222444, name = "Charged Hexsword", popularity = "5.6%" },
            { id = 221062, name = "Scalding Queenmaker's Shiv", popularity = "5.4%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "32.0%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "6.7%" },
            { id = 228906, name = "Operator's Fraud Detector", popularity = "2.6%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "1.7%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "1.5%" }
        },
        TRINKET1 = {
            { id = 230192, name = "BiSMug's Moxie Jug", popularity = "75.1%" },
            { id = 219308, name = "Signet of the Priory", popularity = "37.3%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "33.9%" },
            { id = 219296, name = "Entropic Skardyn Core", popularity = "9.9%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "7.6%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "53.3%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "39.7%" },
            { id = 212265, name = "Tempered Potion", popularity = "49.9%" },
            { id = 222720, name = "The Sushi Special", popularity = "24.6%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "73.4%" }
        }
    }
}
