-- Auto-generated by scraper
WishListData_Priest = {
    DISCIPLINE = {
        icon = "Interface/ICONS/Spell_Holy_PowerWordShield",
        talent = "CAQAAAAAAAAAAAAAAAAAAAAAAAA2mxMGjxYGMz2MbzMzYmZGAAAAAAAAAAwysMbMmZGMLMmxYMYxsNTjJWMAmZBLEGzyAM2wCA",
        statprio = "Mastery > Crit > Haste > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "67.1%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "54.5%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "38.4%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "61.9%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "65.4%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "52.1%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "38.8%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "54.3%" }
        },
        epic_gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "46.6%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "19.9%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "9.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213458, name = "Masterful Ruby", popularity = "53.4%" },
            { id = 213479, name = "Deadly Emerald", popularity = "41.6%" },
            { id = 213455, name = "Quick Ruby", popularity = "39.5%" },
            { id = 213491, name = "Deadly Onyx", popularity = "39.1%" },
            { id = 213482, name = "Masterful Emerald", popularity = "26.8%" }
        },
        HEAD = {
            { id = 229334, name = "Confessor's Unshakable Halo", popularity = "67.5%" },
            { id = 228871, name = "BiSCleanup Crew's Wastemask", popularity = "10.2%" },
            { id = 222818, name = "Consecrated Hood", popularity = "7.5%" },
            { id = 235226, name = "Inventor's Ingenious Trifocals", popularity = "5.2%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "2.0%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "33.9%" },
            { id = 215134, name = "Fractured Gemstone Locket", popularity = "21.1%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "16.2%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "8.4%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "8.0%" }
        },
        SHOULDERS = {
            { id = 229332, name = "BiSConfessor's Unshakable Radiance", popularity = "86.7%" },
            { id = 221072, name = "Moneymaking Businessmantle", popularity = "1.5%" },
            { id = 235812, name = "Shoulderguards of Fraying Sanity", popularity = "1.4%" },
            { id = 222821, name = "Consecrated Mantle", popularity = "1.4%" },
            { id = 235418, name = "Exquisitely Aerodynamic Shoulderpads", popularity = "1.3%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "37.3%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "11.8%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "10.8%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "9.3%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "8.5%" }
        },
        CHEST = {
            { id = 229337, name = "BiSConfessor's Unshakable Vestment", popularity = "88.5%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "1.7%" },
            { id = 222819, name = "Consecrated Robe", popularity = "1.6%" },
            { id = 178792, name = "Soulsewn Vestments", popularity = "1.0%" },
            { id = 235420, name = "Petticoat of the Self-Stylized Azerite Baron", popularity = "0.6%" }
        },
        WRISTS = {
            { id = 222815, name = "Consecrated Cuffs", popularity = "37.4%" },
            { id = 228857, name = "Underparty Admission Bracelet", popularity = "13.9%" },
            { id = 221104, name = "Gleamwax Shackles", popularity = "9.4%" },
            { id = 221037, name = "Charged Rookfeather Wraps", popularity = "7.2%" },
            { id = 229330, name = "Confessor's Unshakable Faulds", popularity = "5.7%" }
        },
        HANDS = {
            { id = 229335, name = "BiSConfessor's Unshakable Mitts", popularity = "85.0%" },
            { id = 221108, name = "King's Malicious Clutches", popularity = "2.9%" },
            { id = 222822, name = "Consecrated Gloves", popularity = "2.2%" },
            { id = 221067, name = "Punctured Apiary Gloves", popularity = "1.5%" },
            { id = 168969, name = "Operator's Mitts", popularity = "1.2%" }
        },
        WAIST = {
            { id = 242664, name = "BiSDurable Information Securing Container", popularity = "90.8%" },
            { id = 222816, name = "Consecrated Cord", popularity = "1.4%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "0.9%" },
            { id = 229331, name = "Confessor's Unshakable Ornament", popularity = "0.9%" },
            { id = 168958, name = "Ringmaster's Cummerbund", popularity = "0.7%" }
        },
        LEGS = {
            { id = 229333, name = "BiSConfessor's Unshakable Leggings", popularity = "83.8%" },
            { id = 221050, name = "Ancient Hardened Legwraps", popularity = "2.5%" },
            { id = 228865, name = "Pit Doctor's Petticoat", popularity = "2.2%" },
            { id = 222820, name = "Consecrated Leggings", popularity = "2.2%" },
            { id = 158350, name = "Rowdy Reveler's Legwraps", popularity = "1.9%" }
        },
        FEET = {
            { id = 222814, name = "Consecrated Slippers", popularity = "23.1%" },
            { id = 229336, name = "Confessor's Unshakable Boots", popularity = "15.9%" },
            { id = 221043, name = "Cloudstrider Soles", popularity = "14.1%" },
            { id = 168964, name = "Hyperthread Boots", popularity = "11.9%" },
            { id = 159235, name = "Deranged Alchemist's Slippers", popularity = "8.3%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "53.7%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "22.6%" },
            { id = 215133, name = "Binding of Binding", popularity = "21.9%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "13.0%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "11.6%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "33.1%" },
            { id = 228901, name = "Big Earner's Bludgeon", popularity = "13.1%" },
            { id = 222439, name = "Everforged Dagger", popularity = "9.5%" },
            { id = 221122, name = "Hand of Beledar", popularity = "6.0%" },
            { id = 221062, name = "Scalding Queenmaker's Shiv", popularity = "5.9%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "27.8%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "11.7%" },
            { id = 228906, name = "Operator's Fraud Detector", popularity = "3.3%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "3.3%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "3.3%" }
        },
        TRINKET1 = {
            { id = 230192, name = "Mug's Moxie Jug", popularity = "63.2%" },
            { id = 230186, name = "BiSMister Pick-Me-Up", popularity = "38.9%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "25.7%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "24.3%" },
            { id = 230198, name = "Eye of Kezan", popularity = "10.1%" }
        },
        consumables = {
            { id = 212271, name = "Flask of Tempered Aggression", popularity = "45.6%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "34.6%" },
            { id = 212265, name = "Tempered Potion", popularity = "16.8%" },
            { id = 222720, name = "The Sushi Special", popularity = "18.1%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "74.2%" }
        }
    },
    HOLY = {
        icon = "Interface/ICONS/Spell_Holy_GuardianSpirit",
        talent = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAMbGGzyYmxMMzDMDjlZmZGAAAAgZZ2G2mZgZhxMGjxYhNzMzUzCAwMLWGmNDAZMYDjlB",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "58.2%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "49.3%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "51.1%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "51.8%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "64.3%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "42.3%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "46.6%" },
            MAINHAND = { id = 223778, name = "Authority of Fiery Resolve", popularity = "42.6%" }
        },
        epic_gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "41.9%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "16.7%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "8.8%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213458, name = "Masterful Ruby", popularity = "38.7%" },
            { id = 213479, name = "Deadly Emerald", popularity = "33.5%" },
            { id = 213491, name = "Deadly Onyx", popularity = "26.7%" },
            { id = 213455, name = "Quick Ruby", popularity = "26.3%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "23.4%" }
        },
        HEAD = {
            { id = 229334, name = "Confessor's Unshakable Halo", popularity = "74.1%" },
            { id = 228871, name = "BiSCleanup Crew's Wastemask", popularity = "6.3%" },
            { id = 235226, name = "Inventor's Ingenious Trifocals", popularity = "3.8%" },
            { id = 222818, name = "Consecrated Hood", popularity = "3.7%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "2.4%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "32.4%" },
            { id = 221103, name = "BiSFlickering Glowtorc", popularity = "21.4%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "16.0%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "9.0%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "3.7%" }
        },
        SHOULDERS = {
            { id = 229332, name = "BiSConfessor's Unshakable Radiance", popularity = "83.9%" },
            { id = 235418, name = "Exquisitely Aerodynamic Shoulderpads", popularity = "2.6%" },
            { id = 235812, name = "Shoulderguards of Fraying Sanity", popularity = "1.8%" },
            { id = 221072, name = "Moneymaking Businessmantle", popularity = "1.6%" },
            { id = 222821, name = "Consecrated Mantle", popularity = "1.2%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "30.8%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "10.3%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "9.3%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "8.9%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "8.9%" }
        },
        CHEST = {
            { id = 229337, name = "BiSConfessor's Unshakable Vestment", popularity = "83.8%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "2.8%" },
            { id = 222819, name = "Consecrated Robe", popularity = "2.7%" },
            { id = 221126, name = "Zealous Warden's Raiment", popularity = "2.2%" },
            { id = 235420, name = "Petticoat of the Self-Stylized Azerite Baron", popularity = "1.3%" }
        },
        WRISTS = {
            { id = 222815, name = "Consecrated Cuffs", popularity = "34.4%" },
            { id = 228857, name = "Underparty Admission Bracelet", popularity = "9.9%" },
            { id = 159240, name = "Rixxa's Sweat-Wicking Cuffs", popularity = "8.8%" },
            { id = 221037, name = "Charged Rookfeather Wraps", popularity = "8.4%" },
            { id = 221104, name = "BiSGleamwax Shackles", popularity = "7.6%" }
        },
        HANDS = {
            { id = 229335, name = "BiSConfessor's Unshakable Mitts", popularity = "78.6%" },
            { id = 222822, name = "Consecrated Gloves", popularity = "3.0%" },
            { id = 221108, name = "King's Malicious Clutches", popularity = "2.9%" },
            { id = 168969, name = "Operator's Mitts", popularity = "2.9%" },
            { id = 221067, name = "Punctured Apiary Gloves", popularity = "2.9%" }
        },
        WAIST = {
            { id = 242664, name = "BiSDurable Information Securing Container", popularity = "87.7%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "1.5%" },
            { id = 222816, name = "Consecrated Cord", popularity = "1.2%" },
            { id = 229331, name = "Confessor's Unshakable Ornament", popularity = "1.1%" },
            { id = 168958, name = "Ringmaster's Cummerbund", popularity = "0.9%" }
        },
        LEGS = {
            { id = 229333, name = "BiSConfessor's Unshakable Leggings", popularity = "83.4%" },
            { id = 228865, name = "Pit Doctor's Petticoat", popularity = "2.8%" },
            { id = 221050, name = "Ancient Hardened Legwraps", popularity = "2.6%" },
            { id = 158350, name = "Rowdy Reveler's Legwraps", popularity = "2.3%" },
            { id = 234495, name = "Razorchoke Slacks", popularity = "1.3%" }
        },
        FEET = {
            { id = 222814, name = "Consecrated Slippers", popularity = "15.8%" },
            { id = 234497, name = "Nonconductive Kill-o-Socks", popularity = "15.0%" },
            { id = 221043, name = "Cloudstrider Soles", popularity = "13.5%" },
            { id = 168964, name = "Hyperthread Boots", popularity = "13.1%" },
            { id = 228847, name = "BiSHotstep Heel-Turners", popularity = "11.9%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "32.7%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "24.9%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "20.9%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "19.9%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "15.7%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "39.2%" },
            { id = 222439, name = "Everforged Dagger", popularity = "7.9%" },
            { id = 228901, name = "BiSBig Earner's Bludgeon", popularity = "6.9%" },
            { id = 159641, name = "G3T-00t", popularity = "5.1%" },
            { id = 178789, name = "Fleshcrafter's Knife", popularity = "5.1%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "24.0%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "5.3%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "4.1%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "3.6%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "3.6%" }
        },
        TRINKET1 = {
            { id = 230186, name = "BiSMister Pick-Me-Up", popularity = "70.1%" },
            { id = 230188, name = "Gallagio Bottle Service", popularity = "22.7%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "20.5%" },
            { id = 219308, name = "Signet of the Priory", popularity = "18.1%" },
            { id = 230192, name = "Mug's Moxie Jug", popularity = "17.8%" }
        },
        consumables = {
            { id = 212271, name = "Flask of Tempered Aggression", popularity = "31.5%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "25.4%" },
            { id = 212241, name = "Algari Mana Potion", popularity = "14.4%" },
            { id = 222720, name = "The Sushi Special", popularity = "17.7%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "67.2%" }
        }
    },
    SHADOW = {
        icon = "Interface/ICONS/Spell_Shadow_ShadowWordPain",
        talent = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDjHAAAAAAAAAAAAghZxMmZmtZbMzMzsNmZZwsxMzMMbMwYMMLmtpmZwCmBwMbWGmNDAZMWAA",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "63.3%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "70.1%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "38.9%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "51.4%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "76.1%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "50.1%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "33.3%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "42.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "38.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "27.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "1.2%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.5%" }
        },
        gems = {
            { id = 213482, name = "Masterful Emerald", popularity = "56.3%" },
            { id = 213494, name = "Quick Onyx", popularity = "49.5%" },
            { id = 213458, name = "Masterful Ruby", popularity = "26.3%" },
            { id = 213455, name = "Quick Ruby", popularity = "20.1%" },
            { id = 213479, name = "Deadly Emerald", popularity = "17.3%" }
        },
        HEAD = {
            { id = 229334, name = "BiSConfessor's Unshakable Halo", popularity = "82.1%" },
            { id = 222818, name = "Consecrated Hood", popularity = "3.4%" },
            { id = 235226, name = "Inventor's Ingenious Trifocals", popularity = "2.2%" },
            { id = 228871, name = "Cleanup Crew's Wastemask", popularity = "1.9%" },
            { id = 212083, name = "Living Luster's Semblance", popularity = "1.4%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "35.3%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "28.3%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "10.1%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "6.1%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "3.8%" }
        },
        SHOULDERS = {
            { id = 229332, name = "BiSConfessor's Unshakable Radiance", popularity = "88.1%" },
            { id = 212081, name = "Living Luster's Dominion", popularity = "1.4%" },
            { id = 222821, name = "Consecrated Mantle", popularity = "1.0%" },
            { id = 211039, name = "Cave Topographer's Shoulders", popularity = "0.7%" },
            { id = 224599, name = "Deep-Dweller's Shoulderpads", popularity = "0.7%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "27.9%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "21.9%" },
            { id = 228844, name = "BiSTest Pilot's Go-Pack", popularity = "8.5%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "7.7%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "7.5%" }
        },
        CHEST = {
            { id = 229337, name = "BiSConfessor's Unshakable Vestment", popularity = "88.8%" },
            { id = 212086, name = "Living Luster's Raiment", popularity = "1.4%" },
            { id = 222819, name = "Consecrated Robe", popularity = "1.1%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "0.9%" },
            { id = 228850, name = "Bottom-Dollar Blouse", popularity = "0.8%" }
        },
        WRISTS = {
            { id = 222815, name = "BiSConsecrated Cuffs", popularity = "49.4%" },
            { id = 228857, name = "Underparty Admission Bracelet", popularity = "7.9%" },
            { id = 228881, name = "Illicit Bankroll Bracers", popularity = "6.6%" },
            { id = 221104, name = "Gleamwax Shackles", popularity = "5.9%" },
            { id = 229330, name = "Confessor's Unshakable Faulds", popularity = "5.2%" }
        },
        HANDS = {
            { id = 229335, name = "BiSConfessor's Unshakable Mitts", popularity = "80.3%" },
            { id = 221067, name = "Punctured Apiary Gloves", popularity = "3.3%" },
            { id = 222822, name = "Consecrated Gloves", popularity = "2.1%" },
            { id = 228872, name = "Golden Handshakers", popularity = "1.9%" },
            { id = 221108, name = "King's Malicious Clutches", popularity = "1.6%" }
        },
        WAIST = {
            { id = 242664, name = "Durable Information Securing Container", popularity = "90.6%" },
            { id = 222816, name = "Consecrated Cord", popularity = "1.5%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "0.9%" },
            { id = 228882, name = "Refiner's Conveyor Belt", popularity = "0.9%" },
            { id = 229331, name = "Confessor's Unshakable Ornament", popularity = "0.7%" }
        },
        LEGS = {
            { id = 229333, name = "Confessor's Unshakable Leggings", popularity = "58.4%" },
            { id = 228865, name = "BiSPit Doctor's Petticoat", popularity = "15.8%" },
            { id = 222820, name = "Consecrated Leggings", popularity = "5.5%" },
            { id = 221050, name = "Ancient Hardened Legwraps", popularity = "4.5%" },
            { id = 158350, name = "Rowdy Reveler's Legwraps", popularity = "3.6%" }
        },
        FEET = {
            { id = 229336, name = "Confessor's Unshakable Boots", popularity = "20.8%" },
            { id = 222814, name = "Consecrated Slippers", popularity = "18.8%" },
            { id = 159235, name = "Deranged Alchemist's Slippers", popularity = "11.9%" },
            { id = 228879, name = "BiSCemented Murloc-Swimmers", popularity = "9.5%" },
            { id = 228847, name = "Hotstep Heel-Turners", popularity = "7.0%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "63.2%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "42.6%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "21.2%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "18.0%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "5.3%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "35.9%" },
            { id = 228901, name = "BiSBig Earner's Bludgeon", popularity = "13.7%" },
            { id = 222439, name = "Everforged Dagger", popularity = "9.7%" },
            { id = 228896, name = "Stix's Metal Detector", popularity = "6.4%" },
            { id = 221122, name = "Hand of Beledar", popularity = "4.0%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "34.3%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "4.0%" },
            { id = 228906, name = "Operator's Fraud Detector", popularity = "3.5%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "2.3%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "1.5%" }
        },
        TRINKET1 = {
            { id = 230192, name = "BiSMug's Moxie Jug", popularity = "70.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "39.3%" },
            { id = 230027, name = "House of Cards", popularity = "26.3%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "11.1%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "8.2%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "47.5%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "39.7%" },
            { id = 212265, name = "Tempered Potion", popularity = "43.9%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "11.8%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "72.8%" }
        }
    }
}
