-- Auto-generated by scraper
WishListData_Druid = {
    BALANCE = {
        icon = "Interface/ICONS/Spell_Nature_StarFall",
        talent = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALUmtmxYmBYWYZmZWYYmFzyMLzMbzMzMzMLmlxwgNsAgxy2MbYMbDgJAAAALmZMAbGGD",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "74.8%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "78.6%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "64.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "71.0%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "85.4%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "59.8%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "64.2%" },
            MAINHAND = { id = 223765, name = "Stonebound Artistry", popularity = "33.5%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "67.0%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "9.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213494, name = "Quick Onyx", popularity = "74.1%" },
            { id = 213482, name = "Masterful Emerald", popularity = "59.0%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "26.5%" },
            { id = 213458, name = "Masterful Ruby", popularity = "26.4%" },
            { id = 213470, name = "Quick Sapphire", popularity = "11.9%" }
        },
        HEAD = {
            { id = 229307, name = "BiSBranches of Reclaiming Blight", popularity = "92.3%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "0.8%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "0.4%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "0.4%" },
            { id = 224602, name = "Underscout's Cap", popularity = "0.4%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "50.6%" },
            { id = 221060, name = "BiSStrapped Rescue-Keg", popularity = "23.0%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "11.6%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "2.6%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "2.3%" }
        },
        SHOULDERS = {
            { id = 229305, name = "BiSJaws of Reclaiming Blight", popularity = "87.7%" },
            { id = 228875, name = "Vandal's Skullplating", popularity = "2.5%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "1.3%" },
            { id = 235811, name = "Extravagant Epaulets", popularity = "0.9%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "0.7%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "48.0%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "18.9%" },
            { id = 228844, name = "BiSTest Pilot's Go-Pack", popularity = "7.8%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "4.5%" },
            { id = 229302, name = "Leaves of Reclaiming Blight", popularity = "3.8%" }
        },
        CHEST = {
            { id = 229310, name = "BiSRobes of Reclaiming Blight", popularity = "75.6%" },
            { id = 228864, name = "\"Streamlined\" Cartel Uniform", popularity = "8.1%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "5.3%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "2.3%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "1.2%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "59.4%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "11.3%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "10.1%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "3.3%" },
            { id = 228869, name = "Killer Queen's Wristflickers", popularity = "3.0%" }
        },
        HANDS = {
            { id = 229308, name = "Grips of Reclaiming Blight", popularity = "63.2%" },
            { id = 221102, name = "BiSShimmering Glimclaws", popularity = "10.5%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "9.6%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "4.7%" },
            { id = 159305, name = "Corrosive Handler's Gloves", popularity = "3.1%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "92.9%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "1.5%" },
            { id = 159725, name = "Unscrupulous Geologist's Belt", popularity = "0.3%" },
            { id = 168957, name = "Mekgineer's Championship Belt", popularity = "0.2%" },
            { id = 221107, name = "Gleamkeeper's Buckle", popularity = "0.2%" }
        },
        LEGS = {
            { id = 229306, name = "BiSBreeches of Reclaiming Blight", popularity = "90.2%" },
            { id = 168968, name = "Flame-Seared Leggings", popularity = "1.6%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.3%" },
            { id = 211018, name = "Treasure-Seeker's Breeches", popularity = "0.6%" },
            { id = 212055, name = "Leggings of the Greatlynx", popularity = "0.4%" }
        },
        FEET = {
            { id = 219327, name = "Rune-Branded Kickers", popularity = "27.0%" },
            { id = 221120, name = "BiSStalwart Guardian's Boots", popularity = "18.8%" },
            { id = 221071, name = "Backbreaking Bootstrappers", popularity = "17.8%" },
            { id = 228876, name = "Dragster's Last Stride", popularity = "7.4%" },
            { id = 229309, name = "Moccasins of Reclaiming Blight", popularity = "6.4%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "73.6%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "40.6%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "33.7%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "18.6%" },
            { id = 221198, name = "85-Year Tenure Ring", popularity = "3.1%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "37.4%" },
            { id = 232805, name = "BiSBest-in-Slots", popularity = "35.0%" },
            { id = 222439, name = "Everforged Dagger", popularity = "3.5%" },
            { id = 221122, name = "Hand of Beledar", popularity = "2.4%" },
            { id = 221032, name = "Voltaic Stormcaller", popularity = "2.1%" }
        },
        OFF_HAND = {
            { id = 222566, name = "Vagabond's Torch", popularity = "7.0%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "2.1%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "2.0%" },
            { id = 221056, name = "Vessel of the Beverage", popularity = "1.0%" },
            { id = 228906, name = "Operator's Fraud Detector", popularity = "1.0%" }
        },
        TRINKET1 = {
            { id = 230192, name = "Mug's Moxie Jug", popularity = "65.8%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "60.2%" },
            { id = 219308, name = "Signet of the Priory", popularity = "22.4%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "14.6%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "7.5%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "60.0%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "52.3%" },
            { id = 212265, name = "Tempered Potion", popularity = "65.1%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "13.1%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "80.7%" }
        }
    },
    FERAL = {
        icon = "Interface/ICONS/Ability_Druid_CatForm",
        talent = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbzmZWYmZmZzmZsNzMzYmBAAAAAYJY2MwMjaGzyYZmZWGzYGAAAAAAAAAAAQzsMLzMbDAYBmZAYhBD",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "71.4%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "73.0%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "51.9%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "68.3%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "84.0%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "53.0%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "51.9%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "41.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "68.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "8.0%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        gems = {
            { id = 213458, name = "Masterful Ruby", popularity = "45.2%" },
            { id = 213491, name = "Deadly Onyx", popularity = "40.8%" },
            { id = 213482, name = "Masterful Emerald", popularity = "37.7%" },
            { id = 213494, name = "Quick Onyx", popularity = "35.6%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "21.4%" }
        },
        HEAD = {
            { id = 229307, name = "BiSBranches of Reclaiming Blight", popularity = "90.6%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "1.0%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "0.9%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "0.5%" },
            { id = 211017, name = "Treasure-Seeker's Helm", popularity = "0.5%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "49.0%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "21.0%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "5.6%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "5.2%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "5.0%" }
        },
        SHOULDERS = {
            { id = 229305, name = "BiSJaws of Reclaiming Blight", popularity = "87.3%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "2.0%" },
            { id = 212054, name = "Maw of the Greatlynx", popularity = "1.4%" },
            { id = 228875, name = "Vandal's Skullplating", popularity = "1.0%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "0.8%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "42.9%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "13.8%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "10.2%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "5.1%" },
            { id = 228844, name = "Test Pilot's Go-Pack", popularity = "4.8%" }
        },
        CHEST = {
            { id = 229310, name = "BiSRobes of Reclaiming Blight", popularity = "86.9%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "2.9%" },
            { id = 212059, name = "Hide of the Greatlynx", popularity = "1.0%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "1.0%" },
            { id = 235417, name = "Venture Co. Plenipotentiary Vest", popularity = "0.9%" }
        },
        WRISTS = {
            { id = 219334, name = "Rune-Branded Armbands", popularity = "51.9%" },
            { id = 234499, name = "BiSDisturbed Kelp Wraps", popularity = "11.8%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "8.3%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "5.8%" },
            { id = 228869, name = "Killer Queen's Wristflickers", popularity = "4.4%" }
        },
        HANDS = {
            { id = 229308, name = "Grips of Reclaiming Blight", popularity = "51.7%" },
            { id = 219333, name = "BiSRune-Branded Grasps", popularity = "15.8%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "8.5%" },
            { id = 159305, name = "Corrosive Handler's Gloves", popularity = "7.0%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "5.1%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "91.8%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "0.9%" },
            { id = 159725, name = "Unscrupulous Geologist's Belt", popularity = "0.4%" },
            { id = 221107, name = "Gleamkeeper's Buckle", popularity = "0.4%" },
            { id = 229304, name = "Wickerbelt of Reclaiming Blight", popularity = "0.4%" }
        },
        LEGS = {
            { id = 229306, name = "BiSBreeches of Reclaiming Blight", popularity = "87.2%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.6%" },
            { id = 168968, name = "Flame-Seared Leggings", popularity = "1.4%" },
            { id = 178801, name = "Fearless Challenger's Leggings", popularity = "1.4%" },
            { id = 221114, name = "Shadowspawn Leggings", popularity = "0.9%" }
        },
        FEET = {
            { id = 219327, name = "Rune-Branded Kickers", popularity = "30.3%" },
            { id = 221120, name = "BiSStalwart Guardian's Boots", popularity = "13.3%" },
            { id = 221071, name = "Backbreaking Bootstrappers", popularity = "11.3%" },
            { id = 178797, name = "Vanquished Usurper's Footpads", popularity = "7.6%" },
            { id = 228876, name = "Dragster's Last Stride", popularity = "6.4%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "68.9%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "46.8%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "17.3%" },
            { id = 178869, name = "Fleshfused Circle", popularity = "11.1%" },
            { id = 221198, name = "85-Year Tenure Ring", popularity = "10.6%" }
        },
        MAIN_HAND = {
            { id = 222448, name = "Charged Halberd", popularity = "31.0%" },
            { id = 232526, name = "BiSBest-in-Slots", popularity = "22.8%" },
            { id = 222567, name = "Vagabond's Careful Crutch", popularity = "7.6%" },
            { id = 221116, name = "Glorious Defender's Poleaxe", popularity = "6.8%" },
            { id = 234494, name = "Gallytech Turbo-Tiller", popularity = "6.8%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "73.7%" },
            { id = 219308, name = "Signet of the Priory", popularity = "54.7%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "27.9%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "5.9%" },
            { id = 235363, name = "Suspicious Energy Drink", popularity = "4.4%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "60.1%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "38.4%" },
            { id = 212265, name = "Tempered Potion", popularity = "58.1%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "12.6%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "74.3%" }
        }
    },
    GUARDIAN = {
        icon = "Interface/ICONS/Ability_Racial_BearForm",
        talent = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzYmhZWmZMjZMzYhZGmFLDYzwoJyMziZbmZWGzYAAAAAAwwYALbzshxsMAmAAAA2MmBgFjhB",
        statprio = "Haste > Vers > Mastery > Crit",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "60.8%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "51.8%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "57.8%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "65.4%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "79.7%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "53.1%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "54.7%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "57.2%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "37.4%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "31.0%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.5%" }
        },
        gems = {
            { id = 213485, name = "Versatile Emerald", popularity = "59.0%" },
            { id = 213470, name = "Quick Sapphire", popularity = "47.8%" },
            { id = 213494, name = "Quick Onyx", popularity = "33.5%" },
            { id = 213482, name = "Masterful Emerald", popularity = "20.9%" },
            { id = 213455, name = "Quick Ruby", popularity = "20.3%" }
        },
        HEAD = {
            { id = 229307, name = "Branches of Reclaiming Blight", popularity = "81.6%" },
            { id = 235224, name = "BiSMekgineer's Mindbending Headgear", popularity = "7.1%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "2.4%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.4%" },
            { id = 235419, name = "High Altitude Turban", popularity = "0.9%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "51.2%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "21.6%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "7.2%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "5.0%" },
            { id = 235429, name = "Moneymaker's Collar", popularity = "3.0%" }
        },
        SHOULDERS = {
            { id = 229305, name = "BiSJaws of Reclaiming Blight", popularity = "77.1%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "5.1%" },
            { id = 221201, name = "Fireproof Cinderbee Perch", popularity = "4.7%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "3.4%" },
            { id = 228875, name = "Vandal's Skullplating", popularity = "2.0%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "39.5%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "13.1%" },
            { id = 199921, name = "Trashmaster's Mantle", popularity = "12.7%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "6.5%" },
            { id = 229302, name = "Leaves of Reclaiming Blight", popularity = "5.7%" }
        },
        CHEST = {
            { id = 229310, name = "BiSRobes of Reclaiming Blight", popularity = "72.8%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "8.2%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "6.9%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "2.5%" },
            { id = 178795, name = "Vest of Concealed Secrets", popularity = "1.7%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "53.8%" },
            { id = 229303, name = "Knots of Reclaiming Blight", popularity = "9.1%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "8.9%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "6.4%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "6.1%" }
        },
        HANDS = {
            { id = 229308, name = "BiSGrips of Reclaiming Blight", popularity = "87.6%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "2.3%" },
            { id = 221102, name = "Shimmering Glimclaws", popularity = "1.4%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "1.1%" },
            { id = 159305, name = "Corrosive Handler's Gloves", popularity = "0.8%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "91.2%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "1.2%" },
            { id = 221058, name = "Brewery Toiler's Waistband", popularity = "1.0%" },
            { id = 219502, name = "Adrenal Surge Clasp", popularity = "0.8%" },
            { id = 159725, name = "Unscrupulous Geologist's Belt", popularity = "0.4%" }
        },
        LEGS = {
            { id = 229306, name = "BiSBreeches of Reclaiming Blight", popularity = "88.6%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.7%" },
            { id = 228854, name = "Bilgerat's Discarded Slacks", popularity = "1.6%" },
            { id = 168968, name = "Flame-Seared Leggings", popularity = "0.8%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "0.8%" }
        },
        FEET = {
            { id = 219327, name = "Rune-Branded Kickers", popularity = "21.2%" },
            { id = 229309, name = "Moccasins of Reclaiming Blight", popularity = "17.3%" },
            { id = 159336, name = "Mercenary Miner's Boots", popularity = "15.8%" },
            { id = 228876, name = "BiSDragster's Last Stride", popularity = "12.6%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "7.7%" }
        },
        FINGER1 = {
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "41.5%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "34.9%" },
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "30.6%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "19.3%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "10.3%" }
        },
        MAIN_HAND = {
            { id = 222448, name = "Charged Halberd", popularity = "28.8%" },
            { id = 232526, name = "BiSBest-in-Slots", popularity = "17.2%" },
            { id = 228892, name = "Greasemonkey's Shift-Stick", popularity = "13.2%" },
            { id = 178865, name = "Xav's Pike of Authority", popularity = "11.4%" },
            { id = 222567, name = "Vagabond's Careful Crutch", popularity = "7.1%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "58.6%" },
            { id = 232543, name = "Ringing Ritual Mud", popularity = "41.6%" },
            { id = 219309, name = "Tome of Light's Devotion", popularity = "16.8%" },
            { id = 230194, name = "BiSReverb Radio", popularity = "11.7%" },
            { id = 219308, name = "Signet of the Priory", popularity = "11.6%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "30.2%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "22.5%" },
            { id = 212265, name = "Tempered Potion", popularity = "30.5%" },
            { id = 222720, name = "The Sushi Special", popularity = "26.0%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "63.6%" }
        }
    },
    RESTORATION = {
        icon = "Interface/ICONS/Spell_Nature_HealingTouch",
        talent = "CkGAAAAAAAAAAAAAAAAAAAAAAsxMzYzMzMzsY2GDGLLjtFbzAAAAAAAAAAAAYbQ2gJDzMjZxsMzYZGzMDAAAAAAAMAAAAAgZbmtmtZWsxYGYYWAN",
        statprio = "Haste > Mastery > Vers > Crit",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "59.4%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "53.9%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "44.8%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "62.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "71.1%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "62.2%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "40.5%" },
            MAINHAND = { id = 223778, name = "Authority of Fiery Resolve", popularity = "40.6%" }
        },
        epic_gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "31.8%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "26.8%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "9.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213482, name = "Masterful Emerald", popularity = "62.8%" },
            { id = 213494, name = "Quick Onyx", popularity = "45.7%" },
            { id = 213470, name = "Quick Sapphire", popularity = "29.9%" },
            { id = 213485, name = "Versatile Emerald", popularity = "21.2%" },
            { id = 213455, name = "Quick Ruby", popularity = "15.1%" }
        },
        HEAD = {
            { id = 229307, name = "Branches of Reclaiming Blight", popularity = "89.8%" },
            { id = 235224, name = "Mekgineer's Mindbending Headgear", popularity = "1.4%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.2%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "0.8%" },
            { id = 235419, name = "High Altitude Turban", popularity = "0.5%" }
        },
        NECK = {
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "36.5%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "34.5%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "5.3%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "4.6%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "4.2%" }
        },
        SHOULDERS = {
            { id = 229305, name = "Jaws of Reclaiming Blight", popularity = "79.5%" },
            { id = 228875, name = "Vandal's Skullplating", popularity = "4.5%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "2.9%" },
            { id = 221201, name = "Fireproof Cinderbee Perch", popularity = "2.8%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "1.9%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "29.6%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "27.6%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "7.4%" },
            { id = 229302, name = "Leaves of Reclaiming Blight", popularity = "6.2%" },
            { id = 228844, name = "Test Pilot's Go-Pack", popularity = "5.2%" }
        },
        CHEST = {
            { id = 229310, name = "Robes of Reclaiming Blight", popularity = "64.9%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "10.3%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "7.5%" },
            { id = 228864, name = "\"Streamlined\" Cartel Uniform", popularity = "3.7%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "3.2%" }
        },
        WRISTS = {
            { id = 219334, name = "Rune-Branded Armbands", popularity = "39.5%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "17.3%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "13.5%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "6.8%" },
            { id = 229303, name = "Knots of Reclaiming Blight", popularity = "4.6%" }
        },
        HANDS = {
            { id = 229308, name = "Grips of Reclaiming Blight", popularity = "83.3%" },
            { id = 221102, name = "Shimmering Glimclaws", popularity = "4.1%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "2.3%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "1.6%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "1.0%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "88.2%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "1.9%" },
            { id = 221058, name = "Brewery Toiler's Waistband", popularity = "1.3%" },
            { id = 159725, name = "Unscrupulous Geologist's Belt", popularity = "0.7%" },
            { id = 221107, name = "Gleamkeeper's Buckle", popularity = "0.6%" }
        },
        LEGS = {
            { id = 229306, name = "Breeches of Reclaiming Blight", popularity = "89.4%" },
            { id = 168968, name = "Flame-Seared Leggings", popularity = "1.3%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.2%" },
            { id = 178801, name = "Fearless Challenger's Leggings", popularity = "0.6%" },
            { id = 212055, name = "Leggings of the Greatlynx", popularity = "0.6%" }
        },
        FEET = {
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "17.7%" },
            { id = 219327, name = "Rune-Branded Kickers", popularity = "16.6%" },
            { id = 221071, name = "Backbreaking Bootstrappers", popularity = "13.7%" },
            { id = 228876, name = "Dragster's Last Stride", popularity = "10.8%" },
            { id = 229309, name = "Moccasins of Reclaiming Blight", popularity = "10.1%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "54.3%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "31.2%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "28.2%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "22.9%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "15.2%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "51.8%" },
            { id = 228896, name = "Stix's Metal Detector", popularity = "5.6%" },
            { id = 232805, name = "Best-in-Slots", popularity = "5.4%" },
            { id = 222439, name = "Everforged Dagger", popularity = "5.3%" },
            { id = 178789, name = "Fleshcrafter's Knife", popularity = "4.1%" }
        },
        OFF_HAND = {
            { id = 222566, name = "Vagabond's Torch", popularity = "12.9%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "3.5%" },
            { id = 228906, name = "Operator's Fraud Detector", popularity = "2.7%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "2.3%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "1.7%" }
        },
        TRINKET1 = {
            { id = 230186, name = "Mister Pick-Me-Up", popularity = "65.5%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "26.4%" },
            { id = 219308, name = "Signet of the Priory", popularity = "18.8%" },
            { id = 230194, name = "Reverb Radio", popularity = "14.2%" },
            { id = 219306, name = "Burin of the Candle King", popularity = "12.0%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "49.0%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "18.3%" },
            { id = 212241, name = "Algari Mana Potion", popularity = "10.6%" },
            { id = 222720, name = "The Sushi Special", popularity = "15.5%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "63.7%" }
        }
    }
}
