-- Auto-generated by scraper
WishListData_Monk = {
    BREWMASTER = {
        icon = "Interface/ICONS/Spell_Monk_Brewmaster_Spec",
        talent = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAAjZGzAzyM2GzMDAAAAAAALLYEzMwMbGbAbzMzwsxMjtZZm22mNbzMjZWAAglZZaZ2mZZAAAAwwG",
        statprio = "Vers > Crit > Mastery > Haste",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "52.8%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "69.2%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "56.7%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "65.0%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "77.5%" },
            RINGS = { id = 223680, name = "Radiant Versatility", popularity = "54.2%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "56.5%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "60.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "56.1%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "12.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213467, name = "Deadly Sapphire", popularity = "69.8%" },
            { id = 213461, name = "Versatile Ruby", popularity = "48.5%" },
            { id = 213497, name = "Versatile Onyx", popularity = "23.9%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "14.8%" },
            { id = 213485, name = "Versatile Emerald", popularity = "12.3%" }
        },
        HEAD = {
            { id = 229298, name = "BiSAgeless Serpent's Mane", popularity = "82.6%" },
            { id = 235419, name = "High Altitude Turban", popularity = "2.1%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "2.0%" },
            { id = 235224, name = "Mekgineer's Mindbending Headgear", popularity = "1.9%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "1.9%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "41.9%" },
            { id = 221103, name = "BiSFlickering Glowtorc", popularity = "31.1%" },
            { id = 211063, name = "Long-Lost Choker", popularity = "4.8%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "4.7%" },
            { id = 232733, name = "Gobfather's Gold Medal", popularity = "2.6%" }
        },
        SHOULDERS = {
            { id = 229296, name = "BiSAgeless Serpent's Shoulderpads", popularity = "86.0%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "2.1%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "1.4%" },
            { id = 211038, name = "Treasure-Seeker's Epaulets", popularity = "1.1%" },
            { id = 212045, name = "Gatecrasher's Enduring Effigy", popularity = "1.1%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "25.6%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "20.2%" },
            { id = 199921, name = "BiSTrashmaster's Mantle", popularity = "14.3%" },
            { id = 229293, name = "Ageless Serpent's Flowing Grace", popularity = "8.7%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "7.4%" }
        },
        CHEST = {
            { id = 229301, name = "Ageless Serpent's Inked Coils", popularity = "69.1%" },
            { id = 219328, name = "BiSRune-Branded Tunic", popularity = "9.9%" },
            { id = 235417, name = "Venture Co. Plenipotentiary Vest", popularity = "4.8%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "4.0%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "2.7%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "57.3%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "6.8%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "6.3%" },
            { id = 228885, name = "Hustler's Ante-Uppers", popularity = "5.1%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "4.5%" }
        },
        HANDS = {
            { id = 229299, name = "BiSAgeless Serpent's Handguards", popularity = "74.5%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "5.6%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "3.1%" },
            { id = 159305, name = "Corrosive Handler's Gloves", popularity = "2.7%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "2.6%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "92.9%" },
            { id = 219502, name = "Adrenal Surge Clasp", popularity = "1.9%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "0.4%" },
            { id = 168986, name = "Mad King's Sporran", popularity = "0.3%" },
            { id = 178805, name = "Girdle of Shattered Dreams", popularity = "0.3%" }
        },
        LEGS = {
            { id = 229297, name = "BiSAgeless Serpent's Leggings", popularity = "87.9%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.9%" },
            { id = 212046, name = "Gatecrasher's Kilt", popularity = "1.3%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "1.3%" },
            { id = 221114, name = "Shadowspawn Leggings", popularity = "0.8%" }
        },
        FEET = {
            { id = 229300, name = "BiSAgeless Serpent's Ankleweights", popularity = "40.5%" },
            { id = 219327, name = "Rune-Branded Kickers", popularity = "19.6%" },
            { id = 228888, name = "Rushed Beta Launchers", popularity = "4.9%" },
            { id = 159336, name = "Mercenary Miner's Boots", popularity = "4.8%" },
            { id = 178797, name = "Vanquished Usurper's Footpads", popularity = "4.5%" }
        },
        FINGER1 = {
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "44.4%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "24.9%" },
            { id = 178870, name = "Ritual Bone Band", popularity = "23.4%" },
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "19.3%" },
            { id = 221200, name = "Radiant Necromancer's Band", popularity = "11.6%" }
        },
        MAIN_HAND = {
            { id = 222448, name = "Charged Halberd", popularity = "35.6%" },
            { id = 222567, name = "Vagabond's Careful Crutch", popularity = "9.9%" },
            { id = 228905, name = "BiSGiga Bank-Breaker", popularity = "8.4%" },
            { id = 234494, name = "Gallytech Turbo-Tiller", popularity = "8.2%" },
            { id = 228892, name = "Greasemonkey's Shift-Stick", popularity = "5.9%" }
        },
        OFF_HAND = {
            { id = 232804, name = "BiSCapo's Molten Knuckles", popularity = "2.1%" },
            { id = 228899, name = "BiSGallywix's Iron Thumb", popularity = "1.9%" },
            { id = 222440, name = "Everforged Longsword", popularity = "1.8%" },
            { id = 221128, name = "Starforged Seraph's Mace", popularity = "1.4%" },
            { id = 221033, name = "Hyperactive Stormclaw", popularity = "1.0%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "66.3%" },
            { id = 232543, name = "BiSRinging Ritual Mud", popularity = "34.3%" },
            { id = 219308, name = "Signet of the Priory", popularity = "28.0%" },
            { id = 219309, name = "BiSTome of Light's Devotion", popularity = "12.9%" },
            { id = 230029, name = "Chromebustible Bomb Suit", popularity = "6.0%" }
        },
        consumables = {
            { id = 212277, name = "Flask of Tempered Versatility", popularity = "51.1%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "29.2%" },
            { id = 212265, name = "Tempered Potion", popularity = "29.7%" },
            { id = 222720, name = "The Sushi Special", popularity = "34.5%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "37.8%" }
        }
    },
    MISTWEAVER = {
        icon = "Interface/ICONS/Spell_Monk_Mistweaver_Spec",
        talent = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLWmZZMLmtZMjNstsMbjHAz2yyMzyCjpZmZgZYGAbzMzwsxYYWegJAAAAAz202sNzysBAAAAbA",
        statprio = "Haste > Crit > Vers > Mastery",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "55.6%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "55.2%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "50.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "64.8%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "72.5%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "61.6%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "46.9%" },
            MAINHAND = { id = 223762, name = "Stormrider's Fury", popularity = "31.4%" }
        },
        epic_gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "35.7%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "30.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "3.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "53.1%" },
            { id = 213485, name = "Versatile Emerald", popularity = "34.7%" },
            { id = 213455, name = "Quick Ruby", popularity = "33.2%" },
            { id = 213470, name = "Quick Sapphire", popularity = "33.0%" },
            { id = 213494, name = "Quick Onyx", popularity = "16.7%" }
        },
        HEAD = {
            { id = 229298, name = "Ageless Serpent's Mane", popularity = "59.0%" },
            { id = 234498, name = "BiSWaterworks Filtration Mask", popularity = "13.9%" },
            { id = 235224, name = "BiSMekgineer's Mindbending Headgear", popularity = "9.2%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "6.1%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "2.0%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "39.6%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "16.7%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "15.2%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "10.8%" },
            { id = 215134, name = "Fractured Gemstone Locket", popularity = "2.3%" }
        },
        SHOULDERS = {
            { id = 229296, name = "BiSAgeless Serpent's Shoulderpads", popularity = "87.9%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "1.7%" },
            { id = 221201, name = "Fireproof Cinderbee Perch", popularity = "1.3%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "0.9%" },
            { id = 228875, name = "Vandal's Skullplating", popularity = "0.9%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "26.2%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "13.4%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "12.7%" },
            { id = 221109, name = "BiSCandlebearer's Shroud", popularity = "10.9%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "9.7%" }
        },
        CHEST = {
            { id = 229301, name = "BiSAgeless Serpent's Inked Coils", popularity = "89.6%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "1.3%" },
            { id = 178795, name = "Vest of Concealed Secrets", popularity = "0.9%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "0.9%" },
            { id = 212050, name = "Gatecrasher's Gi", popularity = "0.8%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "42.7%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "13.2%" },
            { id = 228869, name = "BiSKiller Queen's Wristflickers", popularity = "10.1%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "8.0%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "5.8%" }
        },
        HANDS = {
            { id = 229299, name = "BiSAgeless Serpent's Handguards", popularity = "88.6%" },
            { id = 221102, name = "Shimmering Glimclaws", popularity = "1.0%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "0.9%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "0.9%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "0.8%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "87.9%" },
            { id = 229295, name = "Ageless Serpent's Rope Belt", popularity = "1.7%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "1.3%" },
            { id = 221058, name = "Brewery Toiler's Waistband", popularity = "1.0%" },
            { id = 168986, name = "Mad King's Sporran", popularity = "1.0%" }
        },
        LEGS = {
            { id = 229297, name = "BiSAgeless Serpent's Leggings", popularity = "80.5%" },
            { id = 221114, name = "Shadowspawn Leggings", popularity = "3.7%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "2.3%" },
            { id = 228854, name = "Bilgerat's Discarded Slacks", popularity = "2.0%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "1.9%" }
        },
        FEET = {
            { id = 219327, name = "Rune-Branded Kickers", popularity = "16.2%" },
            { id = 228876, name = "Dragster's Last Stride", popularity = "14.8%" },
            { id = 159336, name = "BiSMercenary Miner's Boots", popularity = "12.6%" },
            { id = 229300, name = "Ageless Serpent's Ankleweights", popularity = "11.3%" },
            { id = 178797, name = "Vanquished Usurper's Footpads", popularity = "10.7%" }
        },
        FINGER1 = {
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "33.2%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "26.4%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "26.1%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "21.7%" },
            { id = 231265, name = "The Jastor Diamond", popularity = "13.6%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "44.3%" },
            { id = 231268, name = "BiSBlastfurious Machete", popularity = "21.2%" },
            { id = 222444, name = "Charged Hexsword", popularity = "5.8%" },
            { id = 168955, name = "Electrifying Cognitive Amplifier", popularity = "4.7%" },
            { id = 221032, name = "Voltaic Stormcaller", popularity = "3.4%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "20.3%" },
            { id = 178868, name = "Deathwalker's Promise", popularity = "5.9%" },
            { id = 221097, name = "Arcane Scuttle", popularity = "3.9%" },
            { id = 228890, name = "Superfan's Beater-Buzzer", popularity = "3.9%" },
            { id = 221056, name = "BiSVessel of the Beverage", popularity = "3.3%" }
        },
        TRINKET1 = {
            { id = 230186, name = "BiSMister Pick-Me-Up", popularity = "79.3%" },
            { id = 230192, name = "Mug's Moxie Jug", popularity = "34.5%" },
            { id = 219310, name = "Bursting Lightshard", popularity = "19.7%" },
            { id = 219308, name = "Signet of the Priory", popularity = "14.7%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "10.0%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "49.5%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "19.8%" },
            { id = 212265, name = "Tempered Potion", popularity = "14.7%" },
            { id = 222720, name = "The Sushi Special", popularity = "29.0%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "66.4%" }
        }
    },
    WINDWALKER = {
        icon = "Interface/ICONS/Spell_Monk_Windwalker_Spec",
        talent = "C0QAAAAAAAAAAAAAAAAAAAAAAYGjBzMjZMzMmZGAAAAAAAAAAAssMMTMzAzwwCDbzMzwsxMDzyMBAwyYmhZY2mBAwyyssMbzMTAAYA",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "59.5%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "71.1%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "47.9%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "64.6%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "79.1%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "47.6%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "45.9%" },
            MAINHAND = { id = 223784, name = "Authority of the Depths", popularity = "41.7%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "62.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.4%" }
        },
        gems = {
            { id = 213494, name = "Quick Onyx", popularity = "49.6%" },
            { id = 213482, name = "Masterful Emerald", popularity = "35.8%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "16.8%" },
            { id = 213497, name = "Versatile Onyx", popularity = "16.7%" },
            { id = 213458, name = "Masterful Ruby", popularity = "16.1%" }
        },
        HEAD = {
            { id = 229298, name = "BiSAgeless Serpent's Mane", popularity = "87.9%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "0.9%" },
            { id = 235224, name = "Mekgineer's Mindbending Headgear", popularity = "0.9%" },
            { id = 212047, name = "Gatecrasher's Horns", popularity = "0.9%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "0.9%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "42.4%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "18.4%" },
            { id = 228842, name = "BiSGobfather's Gifted Bling", popularity = "11.7%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "6.3%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "3.9%" }
        },
        SHOULDERS = {
            { id = 229296, name = "BiSAgeless Serpent's Shoulderpads", popularity = "84.8%" },
            { id = 228875, name = "Vandal's Skullplating", popularity = "2.0%" },
            { id = 235811, name = "Extravagant Epaulets", popularity = "1.8%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "1.6%" },
            { id = 212045, name = "Gatecrasher's Enduring Effigy", popularity = "1.5%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "38.7%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "15.1%" },
            { id = 228844, name = "Test Pilot's Go-Pack", popularity = "6.2%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "6.2%" },
            { id = 229293, name = "Ageless Serpent's Flowing Grace", popularity = "5.9%" }
        },
        CHEST = {
            { id = 229301, name = "BiSAgeless Serpent's Inked Coils", popularity = "85.2%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "2.3%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "1.7%" },
            { id = 235417, name = "Venture Co. Plenipotentiary Vest", popularity = "1.2%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "0.9%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "52.0%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "10.9%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "7.4%" },
            { id = 229294, name = "Ageless Serpent's Cuffs", popularity = "5.9%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "4.1%" }
        },
        HANDS = {
            { id = 229299, name = "BiSAgeless Serpent's Handguards", popularity = "83.4%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "2.3%" },
            { id = 221102, name = "Shimmering Glimclaws", popularity = "2.3%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "1.3%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "1.2%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "91.0%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "1.3%" },
            { id = 229295, name = "Ageless Serpent's Rope Belt", popularity = "0.6%" },
            { id = 168957, name = "Mekgineer's Championship Belt", popularity = "0.5%" },
            { id = 221058, name = "Brewery Toiler's Waistband", popularity = "0.3%" }
        },
        LEGS = {
            { id = 229297, name = "Ageless Serpent's Leggings", popularity = "60.4%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "9.3%" },
            { id = 168968, name = "BiSFlame-Seared Leggings", popularity = "9.3%" },
            { id = 211018, name = "Treasure-Seeker's Breeches", popularity = "3.6%" },
            { id = 178801, name = "Fearless Challenger's Leggings", popularity = "3.4%" }
        },
        FEET = {
            { id = 219327, name = "Rune-Branded Kickers", popularity = "24.7%" },
            { id = 221071, name = "BiSBackbreaking Bootstrappers", popularity = "14.1%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "11.6%" },
            { id = 229300, name = "Ageless Serpent's Ankleweights", popularity = "10.4%" },
            { id = 228876, name = "Dragster's Last Stride", popularity = "8.5%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "63.0%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "52.9%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "17.9%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "10.2%" },
            { id = 178869, name = "Fleshfused Circle", popularity = "7.0%" }
        },
        MAIN_HAND = {
            { id = 222448, name = "Charged Halberd", popularity = "27.1%" },
            { id = 228892, name = "Greasemonkey's Shift-Stick", popularity = "13.1%" },
            { id = 221116, name = "BiSGlorious Defender's Poleaxe", popularity = "12.0%" },
            { id = 234494, name = "Gallytech Turbo-Tiller", popularity = "7.5%" },
            { id = 222567, name = "Vagabond's Careful Crutch", popularity = "7.3%" }
        },
        OFF_HAND = {
            { id = 228899, name = "BiSGallywix's Iron Thumb", popularity = "2.2%" },
            { id = 232804, name = "BiSCapo's Molten Knuckles", popularity = "1.6%" },
            { id = 228904, name = "Crowd Favorite", popularity = "1.4%" },
            { id = 222440, name = "Everforged Longsword", popularity = "1.2%" },
            { id = 222446, name = "Charged Facesmasher", popularity = "1.1%" }
        },
        TRINKET1 = {
            { id = 230027, name = "BiSHouse of Cards", popularity = "63.3%" },
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "59.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "15.2%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "7.8%" },
            { id = 234217, name = "Funhouse Lens", popularity = "6.2%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "52.5%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "41.0%" },
            { id = 212265, name = "Tempered Potion", popularity = "49.3%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "10.7%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "61.1%" }
        }
    }
}
