-- Auto-generated by scraper
WishListData_Deathknight = {
    BLOOD = {
        icon = "Interface/ICONS/Spell_Deathknight_BloodPresence",
        talent = "CoPAAAAAAAAAAAAAAAAAAAAAAghxMzYMjZmZYMjZmmhxMzYGAAAAAgZmZmZmZmtHwMDAAAmZmZmBAAAwADMjRjlNAbDYbAMD2A",
        statprio = "Strength > Haste > Mastery > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "54.2%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "73.1%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "33.9%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "59.3%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "75.7%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "42.4%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "36.5%" },
            MAINHAND = { id = nil, name = "Rune of the Fallen Crusader", popularity = "56.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "40.7%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "27.0%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.5%" }
        },
        gems = {
            { id = 213482, name = "Masterful Emerald", popularity = "37.1%" },
            { id = 213485, name = "Versatile Emerald", popularity = "26.0%" },
            { id = 213470, name = "Quick Sapphire", popularity = "25.8%" },
            { id = 213494, name = "Quick Onyx", popularity = "24.8%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "22.3%" }
        },
        HEAD = {
            { id = 229253, name = "BiSCauldron Champion's Crown", popularity = "84.6%" },
            { id = 222433, name = "Everforged Helm", popularity = "2.2%" },
            { id = 228858, name = "Fullthrottle Facerig", popularity = "1.9%" },
            { id = 221047, name = "Monstrosity's Gaze", popularity = "1.6%" },
            { id = 235222, name = "Apogee Inventor's Goggles", popularity = "1.2%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "43.8%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "20.7%" },
            { id = 221103, name = "BiSFlickering Glowtorc", popularity = "10.6%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "7.1%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "2.5%" }
        },
        SHOULDERS = {
            { id = 229251, name = "BiSCauldron Champion's Screamplate", popularity = "87.0%" },
            { id = 178802, name = "Unyielding Combatant's Pauldrons", popularity = "1.3%" },
            { id = 235415, name = "Skyscorcher Pauldrons", popularity = "1.2%" },
            { id = 221052, name = "Foam-Ridden Pauldrons", popularity = "1.2%" },
            { id = 222436, name = "Everforged Pauldrons", popularity = "1.1%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "41.5%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "12.8%" },
            { id = 229248, name = "Cauldron Champion's Spined Cloak", popularity = "6.6%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "6.4%" },
            { id = 199921, name = "Trashmaster's Mantle", popularity = "5.9%" }
        },
        CHEST = {
            { id = 229256, name = "BiSCauldron Champion's Ribcage", popularity = "83.6%" },
            { id = 222430, name = "Everforged Breastplate", popularity = "2.9%" },
            { id = 178793, name = "Abdominal Securing Chestguard", popularity = "1.7%" },
            { id = 234506, name = "BiSMuckdiver's Wading Plate", popularity = "1.7%" },
            { id = 228851, name = "\"Bullet-Proof\" Vestplate", popularity = "1.0%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "50.0%" },
            { id = 229249, name = "Cauldron Champion's Wraps", popularity = "8.1%" },
            { id = 158359, name = "Stonefury Vambraces", popularity = "6.4%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "5.5%" },
            { id = 221064, name = "Fuzzy Cindercuffs", popularity = "5.3%" }
        },
        HANDS = {
            { id = 229254, name = "BiSCauldron Champion's Fistguards", popularity = "81.3%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "3.0%" },
            { id = 228849, name = "Dumpmech Compactors", popularity = "2.3%" },
            { id = 221112, name = "Caliginous Claspers", popularity = "2.2%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "1.7%" }
        },
        WAIST = {
            { id = 245966, name = "BiSDurable Information Securing Container", popularity = "88.4%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "2.2%" },
            { id = 221040, name = "Lightning-Conductor's Bands", popularity = "1.6%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "0.9%" },
            { id = 168976, name = "Automatic Waist Tightener", popularity = "0.8%" }
        },
        LEGS = {
            { id = 229252, name = "BiSCauldron Champion's Tattered Cuisses", popularity = "65.9%" },
            { id = 222434, name = "Everforged Legplates", popularity = "7.5%" },
            { id = 178800, name = "BiSGalvanized Oxxein Legguards", popularity = "6.2%" },
            { id = 221034, name = "Thunder-Clad Legguards", popularity = "5.7%" },
            { id = 168966, name = "Heavy Alloy Legplates", popularity = "3.4%" }
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "26.1%" },
            { id = 229255, name = "Cauldron Champion's Greatboots", popularity = "18.3%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "9.9%" },
            { id = 228874, name = "Rik's Walkin' Boots", popularity = "9.4%" },
            { id = 159679, name = "BiSSabatons of Rampaging Elements", popularity = "7.7%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "45.9%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "35.2%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "20.4%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "14.4%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "12.6%" }
        },
        MAIN_HAND = {
            { id = 222447, name = "Charged Claymore", popularity = "21.4%" },
            { id = 232526, name = "BiSBest-in-Slots", popularity = "16.2%" },
            { id = 222443, name = "Everforged Greataxe", popularity = "8.0%" },
            { id = 234490, name = "Circuit Breaker", popularity = "7.3%" },
            { id = 221111, name = "Poleaxe of Somber Fate", popularity = "6.9%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "56.5%" },
            { id = 219309, name = "BiSTome of Light's Devotion", popularity = "45.3%" },
            { id = 232543, name = "Ringing Ritual Mud", popularity = "12.4%" },
            { id = 230029, name = "Chromebustible Bomb Suit", popularity = "11.5%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "9.0%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "34.2%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "21.4%" },
            { id = 212265, name = "Tempered Potion", popularity = "27.7%" },
            { id = 222720, name = "The Sushi Special", popularity = "23.1%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "64.1%" }
        }
    },
    FROST = {
        icon = "Interface/ICONS/Spell_Deathknight_FrostPresence",
        talent = "CsPAAAAAAAAAAAAAAAAAAAAAAAgZGjhZYGjZmZmZmxMmJzYYYGMzYmhZmZmZmZZmBAAAAAAAAAAAYssNwAWALDTgxCmZmxMA",
        statprio = "Strength > Mastery > Crit > Haste > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "63.7%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "76.1%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "41.8%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "51.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "78.4%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "56.1%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "33.9%" },
            MAINHAND = { id = nil, name = "Rune of Razorice", popularity = "58.6%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "62.8%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "7.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.6%" }
        },
        gems = {
            { id = 213458, name = "Masterful Ruby", popularity = "63.5%" },
            { id = 213491, name = "Deadly Onyx", popularity = "34.6%" },
            { id = 213482, name = "Masterful Emerald", popularity = "25.0%" },
            { id = 213479, name = "Deadly Emerald", popularity = "20.0%" },
            { id = 213494, name = "Quick Onyx", popularity = "16.4%" }
        },
        HEAD = {
            { id = 229253, name = "Cauldron Champion's Crown", popularity = "54.4%" },
            { id = 228858, name = "BiSFullthrottle Facerig", popularity = "14.5%" },
            { id = 222433, name = "Everforged Helm", popularity = "11.4%" },
            { id = 235222, name = "Apogee Inventor's Goggles", popularity = "8.0%" },
            { id = 211029, name = "Secret-Dredger's Helm", popularity = "1.5%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "51.5%" },
            { id = 221060, name = "BiSStrapped Rescue-Keg", popularity = "12.1%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "8.3%" },
            { id = 235428, name = "Gobtastic Bling", popularity = "4.8%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "3.8%" }
        },
        SHOULDERS = {
            { id = 229251, name = "BiSCauldron Champion's Screamplate", popularity = "89.6%" },
            { id = 212000, name = "Exhumed Centurion's Spikes", popularity = "1.0%" },
            { id = 235415, name = "Skyscorcher Pauldrons", popularity = "0.8%" },
            { id = 211034, name = "Secret-Dredger's Mantle", popularity = "0.6%" },
            { id = 221203, name = "Reanimator's Pyreforged Shoulders", popularity = "0.6%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "34.9%" },
            { id = 221054, name = "BiSChef Chewie's Towel", popularity = "13.8%" },
            { id = 229248, name = "Cauldron Champion's Spined Cloak", popularity = "10.7%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "9.8%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "6.0%" }
        },
        CHEST = {
            { id = 229256, name = "BiSCauldron Champion's Ribcage", popularity = "88.6%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "1.4%" },
            { id = 222430, name = "Everforged Breastplate", popularity = "0.9%" },
            { id = 212005, name = "Exhumed Centurion's Breastplate", popularity = "0.8%" },
            { id = 211030, name = "Secret-Dredger's Breastplate", popularity = "0.7%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "51.0%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "8.4%" },
            { id = 228884, name = "Test Subject's Clasps", popularity = "6.5%" },
            { id = 228868, name = "Revved-Up Vambraces", popularity = "6.1%" },
            { id = 158359, name = "Stonefury Vambraces", popularity = "5.7%" }
        },
        HANDS = {
            { id = 229254, name = "BiSCauldron Champion's Fistguards", popularity = "88.0%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "1.3%" },
            { id = 168980, name = "Gauntlets of Absolute Authority", popularity = "1.0%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "0.8%" },
            { id = 155864, name = "Power-Assisted Vicegrips", popularity = "0.7%" }
        },
        WAIST = {
            { id = 245966, name = "BiSDurable Information Securing Container", popularity = "92.0%" },
            { id = 229250, name = "Cauldron Champion's Title Belt", popularity = "0.8%" },
            { id = 168976, name = "Automatic Waist Tightener", popularity = "0.7%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "0.7%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "0.5%" }
        },
        LEGS = {
            { id = 229252, name = "BiSCauldron Champion's Tattered Cuisses", popularity = "83.1%" },
            { id = 222434, name = "Everforged Legplates", popularity = "4.5%" },
            { id = 178800, name = "Galvanized Oxxein Legguards", popularity = "1.6%" },
            { id = 159451, name = "Leadplate Legguards", popularity = "1.3%" },
            { id = 212001, name = "Exhumed Centurion's Chausses", popularity = "0.9%" }
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "24.9%" },
            { id = 229255, name = "Cauldron Champion's Greatboots", popularity = "15.3%" },
            { id = 221061, name = "BiSHops-Laden Greatboots", popularity = "12.6%" },
            { id = 228874, name = "Rik's Walkin' Boots", popularity = "10.5%" },
            { id = 159679, name = "Sabatons of Rampaging Elements", popularity = "9.5%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "59.6%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "31.4%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "24.1%" },
            { id = 221197, name = "Hoop of the Blighted", popularity = "15.6%" },
            { id = 178872, name = "Ring of Perpetual Conflict", popularity = "14.2%" }
        },
        MAIN_HAND = {
            { id = 222451, name = "BiSCharged Slicer", popularity = "24.0%" },
            { id = 222440, name = "Everforged Longsword", popularity = "19.8%" },
            { id = 228895, name = "BiSRemixed Ignition Saber", popularity = "15.7%" },
            { id = 178863, name = "Gorestained Cleaver", popularity = "5.5%" },
            { id = 169608, name = "Tearing Sawtooth Blade", popularity = "4.4%" }
        },
        OFF_HAND = {
            { id = 222451, name = "BiSCharged Slicer", popularity = "25.0%" },
            { id = 222440, name = "Everforged Longsword", popularity = "20.4%" },
            { id = 228895, name = "BiSRemixed Ignition Saber", popularity = "11.5%" },
            { id = 228902, name = "Wiseguy's Refused Offer", popularity = "5.0%" },
            { id = 178863, name = "Gorestained Cleaver", popularity = "3.4%" }
        },
        TRINKET1 = {
            { id = 230027, name = "BiSHouse of Cards", popularity = "70.5%" },
            { id = 232541, name = "BiSImprovised Seaforium Pacemaker", popularity = "69.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "14.4%" },
            { id = 235363, name = "Suspicious Energy Drink", popularity = "5.4%" },
            { id = 230198, name = "Eye of Kezan", popularity = "5.2%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "45.1%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "34.9%" },
            { id = 212265, name = "Tempered Potion", popularity = "51.7%" },
            { id = 222720, name = "The Sushi Special", popularity = "11.1%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "64.9%" }
        }
    },
    UNHOLY = {
        icon = "Interface/ICONS/Spell_Deathknight_UnholyPresence",
        talent = "CwPAAAAAAAAAAAAAAAAAAAAAAAgZmZMjxMDjZMzMNMMzMzYAAAAAAAAAgZYmZMzMDAMbmhZZYmZmHYmxYgBmxoxyCgtBbAwMA",
        statprio = "Strength > Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "77.5%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "84.8%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "58.2%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "59.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "87.0%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "69.6%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "46.0%" },
            MAINHAND = { id = nil, name = "Rune of the Fallen Crusader", popularity = "94.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "58.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "15.8%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.1%" }
        },
        gems = {
            { id = 213482, name = "Masterful Emerald", popularity = "79.6%" },
            { id = 213494, name = "Quick Onyx", popularity = "57.0%" },
            { id = 213470, name = "Quick Sapphire", popularity = "24.6%" },
            { id = 213455, name = "Quick Ruby", popularity = "18.8%" },
            { id = 213485, name = "Versatile Emerald", popularity = "15.6%" }
        },
        HEAD = {
            { id = 229253, name = "BiSCauldron Champion's Crown", popularity = "92.1%" },
            { id = 222433, name = "Everforged Helm", popularity = "1.2%" },
            { id = 221100, name = "Waxsteel Greathelm", popularity = "0.5%" },
            { id = 228858, name = "Fullthrottle Facerig", popularity = "0.4%" },
            { id = 221047, name = "Monstrosity's Gaze", popularity = "0.3%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "47.5%" },
            { id = 221060, name = "BiSStrapped Rescue-Keg", popularity = "36.1%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "4.3%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "2.5%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "1.2%" }
        },
        SHOULDERS = {
            { id = 229251, name = "BiSCauldron Champion's Screamplate", popularity = "93.4%" },
            { id = 178802, name = "Unyielding Combatant's Pauldrons", popularity = "0.6%" },
            { id = 222436, name = "Everforged Pauldrons", popularity = "0.5%" },
            { id = 212000, name = "Exhumed Centurion's Spikes", popularity = "0.3%" },
            { id = 211034, name = "Secret-Dredger's Mantle", popularity = "0.2%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "58.1%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "16.3%" },
            { id = 228844, name = "Test Pilot's Go-Pack", popularity = "8.1%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "2.8%" },
            { id = 229248, name = "Cauldron Champion's Spined Cloak", popularity = "2.4%" }
        },
        CHEST = {
            { id = 229256, name = "BiSCauldron Champion's Ribcage", popularity = "92.2%" },
            { id = 228851, name = "\"Bullet-Proof\" Vestplate", popularity = "0.9%" },
            { id = 222430, name = "Everforged Breastplate", popularity = "0.8%" },
            { id = 211030, name = "Secret-Dredger's Breastplate", popularity = "0.4%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "0.4%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "66.8%" },
            { id = 158359, name = "Stonefury Vambraces", popularity = "9.8%" },
            { id = 229249, name = "Cauldron Champion's Wraps", popularity = "5.8%" },
            { id = 228868, name = "Revved-Up Vambraces", popularity = "3.1%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "2.3%" }
        },
        HANDS = {
            { id = 229254, name = "BiSCauldron Champion's Fistguards", popularity = "90.0%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "2.0%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "1.2%" },
            { id = 211032, name = "Secret-Dredger's Gauntlets", popularity = "0.4%" },
            { id = 168980, name = "Gauntlets of Absolute Authority", popularity = "0.4%" }
        },
        WAIST = {
            { id = 245966, name = "BiSDurable Information Securing Container", popularity = "93.0%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "0.9%" },
            { id = 221040, name = "Lightning-Conductor's Bands", popularity = "0.9%" },
            { id = 228886, name = "Coin-Operated Girdle", popularity = "0.4%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "0.2%" }
        },
        LEGS = {
            { id = 222434, name = "Everforged Legplates", popularity = "39.1%" },
            { id = 229252, name = "Cauldron Champion's Tattered Cuisses", popularity = "25.8%" },
            { id = 178800, name = "BiSGalvanized Oxxein Legguards", popularity = "21.1%" },
            { id = 221034, name = "Thunder-Clad Legguards", popularity = "3.6%" },
            { id = 211033, name = "Secret-Dredger's Legguards", popularity = "1.5%" }
        },
        FEET = {
            { id = 229255, name = "BiSCauldron Champion's Greatboots", popularity = "36.3%" },
            { id = 222429, name = "Everforged Sabatons", popularity = "25.2%" },
            { id = 228874, name = "Rik's Walkin' Boots", popularity = "22.3%" },
            { id = 211031, name = "Secret-Dredger's Sabatons", popularity = "2.4%" },
            { id = 221061, name = "Hops-Laden Greatboots", popularity = "2.4%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "69.7%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "53.9%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "26.1%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "14.3%" },
            { id = 228843, name = "BiSMiniature Roulette Wheel", popularity = "4.0%" }
        },
        MAIN_HAND = {
            { id = 232526, name = "BiSBest-in-Slots", popularity = "39.7%" },
            { id = 222447, name = "Charged Claymore", popularity = "19.8%" },
            { id = 234490, name = "Circuit Breaker", popularity = "7.4%" },
            { id = 159638, name = "Electro-Arm Bludgeoner", popularity = "5.9%" },
            { id = 222443, name = "Everforged Greataxe", popularity = "5.7%" }
        },
        TRINKET1 = {
            { id = 230027, name = "BiSHouse of Cards", popularity = "85.3%" },
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "43.0%" },
            { id = 235363, name = "Suspicious Energy Drink", popularity = "22.9%" },
            { id = 230198, name = "Eye of Kezan", popularity = "17.1%" },
            { id = 219308, name = "Signet of the Priory", popularity = "5.9%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "44.3%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "44.5%" },
            { id = 212265, name = "Tempered Potion", popularity = "70.8%" },
            { id = 222720, name = "The Sushi Special", popularity = "13.2%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "80.2%" }
        }
    }
}
