-- Auto-generated by scraper
WishListData_Demonhunter = {
    HAVOC = {
        icon = "Interface/ICONS/Ability_DemonHunter_SpecDPS",
        talent = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZmZmZmZMzMjxMZGzAAAAAAAmFjxMMzMbjZ2wyMDGDjltZbGMM22YCzYmZYYB",
        statprio = "Mastery > Crit > Haste > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "59.0%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "76.4%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "45.2%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "65.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "79.5%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "64.0%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "45.5%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "54.3%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "68.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "3.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.5%" }
        },
        gems = {
            { id = 213458, name = "Masterful Ruby", popularity = "68.4%" },
            { id = 213491, name = "Deadly Onyx", popularity = "45.3%" },
            { id = 213479, name = "Deadly Emerald", popularity = "36.4%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "24.8%" },
            { id = 213455, name = "Quick Ruby", popularity = "18.8%" }
        },
        HEAD = {
            { id = 229316, name = "BiSFel-Dealer's Visor", popularity = "78.5%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "5.3%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "3.2%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "2.0%" },
            { id = 228848, name = "Darkfuse Racketeer's Tricorne", popularity = "1.8%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "55.7%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "12.7%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "6.4%" },
            { id = 235428, name = "Gobtastic Bling", popularity = "3.8%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "3.6%" }
        },
        SHOULDERS = {
            { id = 229314, name = "BiSFel-Dealer's Recycled Reavers", popularity = "89.9%" },
            { id = 235811, name = "Extravagant Epaulets", popularity = "1.0%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "0.8%" },
            { id = 211038, name = "Treasure-Seeker's Epaulets", popularity = "0.8%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "0.8%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "33.3%" },
            { id = 221054, name = "BiSChef Chewie's Towel", popularity = "21.2%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "7.7%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "6.4%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "5.8%" }
        },
        CHEST = {
            { id = 229319, name = "BiSFel-Dealer's Soul Engine", popularity = "87.7%" },
            { id = 235417, name = "Venture Co. Plenipotentiary Vest", popularity = "2.2%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "1.4%" },
            { id = 178795, name = "Vest of Concealed Secrets", popularity = "1.0%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "0.8%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "58.6%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "7.2%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "6.0%" },
            { id = 228869, name = "Killer Queen's Wristflickers", popularity = "5.6%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "4.9%" }
        },
        HANDS = {
            { id = 229317, name = "BiSFel-Dealer's Underhandlers", popularity = "64.4%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "8.3%" },
            { id = 221036, name = "BiSTempestwind Handlers", popularity = "6.6%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "5.9%" },
            { id = 159305, name = "Corrosive Handler's Gloves", popularity = "4.9%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "92.2%" },
            { id = 221107, name = "Gleamkeeper's Buckle", popularity = "0.8%" },
            { id = 229313, name = "Fel-Dealer's Waistwrap", popularity = "0.5%" },
            { id = 159725, name = "Unscrupulous Geologist's Belt", popularity = "0.5%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "0.4%" }
        },
        LEGS = {
            { id = 229315, name = "BiSFel-Dealer's Fur Kilt", popularity = "86.0%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "2.3%" },
            { id = 178801, name = "Fearless Challenger's Leggings", popularity = "2.0%" },
            { id = 221114, name = "Shadowspawn Leggings", popularity = "1.6%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "0.8%" }
        },
        FEET = {
            { id = 229318, name = "Fel-Dealer's Smugglers", popularity = "28.1%" },
            { id = 219327, name = "Rune-Branded Kickers", popularity = "21.5%" },
            { id = 228888, name = "BiSRushed Beta Launchers", popularity = "10.9%" },
            { id = 168975, name = "Machinist's Treasured Treads", popularity = "7.8%" },
            { id = 178797, name = "Vanquished Usurper's Footpads", popularity = "5.8%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "56.9%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "23.3%" },
            { id = 178872, name = "BiSRing of Perpetual Conflict", popularity = "21.6%" },
            { id = 221197, name = "Hoop of the Blighted", popularity = "19.3%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "18.9%" }
        },
        MAIN_HAND = {
            { id = 222441, name = "BiSEverforged Warglaive", popularity = "43.9%" },
            { id = 232804, name = "BiSCapo's Molten Knuckles", popularity = "15.5%" },
            { id = 222440, name = "Everforged Longsword", popularity = "10.5%" },
            { id = 234491, name = "Sonic Ka-BOOM!-erang", popularity = "8.7%" },
            { id = 228894, name = "GIGADEATH Chainblade", popularity = "5.0%" }
        },
        OFF_HAND = {
            { id = 222441, name = "BiSEverforged Warglaive", popularity = "35.4%" },
            { id = 232804, name = "BiSCapo's Molten Knuckles", popularity = "19.6%" },
            { id = 222440, name = "Everforged Longsword", popularity = "10.4%" },
            { id = 228894, name = "GIGADEATH Chainblade", popularity = "9.0%" },
            { id = 234491, name = "Sonic Ka-BOOM!-erang", popularity = "5.9%" }
        },
        TRINKET1 = {
            { id = 232541, name = "BiSImprovised Seaforium Pacemaker", popularity = "78.8%" },
            { id = 219308, name = "Signet of the Priory", popularity = "45.1%" },
            { id = 230027, name = "House of Cards", popularity = "22.1%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "9.1%" },
            { id = 235363, name = "Suspicious Energy Drink", popularity = "4.9%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "54.8%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "39.4%" },
            { id = 212265, name = "Tempered Potion", popularity = "48.4%" },
            { id = 222720, name = "The Sushi Special", popularity = "18.1%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "67.0%" }
        }
    },
    VENGEANCE = {
        icon = "Interface/ICONS/Ability_DemonHunter_SpecTank",
        talent = "CUkAAAAAAAAAAAAAAAAAAAAAAAAmZMmZMMjMzMMDzMbjxMsNDzMmZMY2mZmNzMmZYGAAAAmtZwwYZhJMYmZwC",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "68.2%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "77.7%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "66.5%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "67.7%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "85.5%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "64.6%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "64.1%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "69.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "61.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "15.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "74.2%" },
            { id = 213455, name = "Quick Ruby", popularity = "56.6%" },
            { id = 213470, name = "Quick Sapphire", popularity = "33.7%" },
            { id = 213485, name = "Versatile Emerald", popularity = "24.5%" },
            { id = 213494, name = "Quick Onyx", popularity = "20.5%" }
        },
        HEAD = {
            { id = 229316, name = "BiSFel-Dealer's Visor", popularity = "88.3%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "3.1%" },
            { id = 235224, name = "Mekgineer's Mindbending Headgear", popularity = "1.3%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "1.1%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "0.7%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "51.8%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "18.0%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "13.1%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "7.7%" },
            { id = 235429, name = "Moneymaker's Collar", popularity = "0.9%" }
        },
        SHOULDERS = {
            { id = 229314, name = "BiSFel-Dealer's Recycled Reavers", popularity = "87.2%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "2.4%" },
            { id = 221201, name = "Fireproof Cinderbee Perch", popularity = "2.1%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "1.6%" },
            { id = 228875, name = "Vandal's Skullplating", popularity = "1.0%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "36.1%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "16.4%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "9.8%" },
            { id = 229311, name = "Fel-Dealer's Fur Shawl", popularity = "8.3%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "7.5%" }
        },
        CHEST = {
            { id = 229319, name = "BiSFel-Dealer's Soul Engine", popularity = "93.2%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "0.6%" },
            { id = 178795, name = "Vest of Concealed Secrets", popularity = "0.6%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "0.5%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "0.3%" }
        },
        WRISTS = {
            { id = 219334, name = "Rune-Branded Armbands", popularity = "47.5%" },
            { id = 158353, name = "BiSServo-Arm Bindings", popularity = "17.4%" },
            { id = 228869, name = "Killer Queen's Wristflickers", popularity = "10.7%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "7.2%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "5.5%" }
        },
        HANDS = {
            { id = 229317, name = "BiSFel-Dealer's Underhandlers", popularity = "88.2%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "1.9%" },
            { id = 221102, name = "Shimmering Glimclaws", popularity = "1.2%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "1.2%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "1.1%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "92.5%" },
            { id = 219502, name = "Adrenal Surge Clasp", popularity = "1.3%" },
            { id = 229313, name = "Fel-Dealer's Waistwrap", popularity = "0.8%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "0.5%" },
            { id = 221058, name = "Brewery Toiler's Waistband", popularity = "0.3%" }
        },
        LEGS = {
            { id = 229315, name = "Fel-Dealer's Fur Kilt", popularity = "46.2%" },
            { id = 221114, name = "BiSShadowspawn Leggings", popularity = "17.9%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "13.9%" },
            { id = 228854, name = "Bilgerat's Discarded Slacks", popularity = "6.7%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "4.5%" }
        },
        FEET = {
            { id = 219327, name = "Rune-Branded Kickers", popularity = "20.9%" },
            { id = 178797, name = "Vanquished Usurper's Footpads", popularity = "16.7%" },
            { id = 168975, name = "Machinist's Treasured Treads", popularity = "15.9%" },
            { id = 228876, name = "BiSDragster's Last Stride", popularity = "14.9%" },
            { id = 159336, name = "Mercenary Miner's Boots", popularity = "9.5%" }
        },
        FINGER1 = {
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "39.7%" },
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "34.1%" },
            { id = 178871, name = "BiSBloodoath Signet", popularity = "28.9%" },
            { id = 215133, name = "Binding of Binding", popularity = "19.2%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "17.3%" }
        },
        MAIN_HAND = {
            { id = 222441, name = "Everforged Warglaive", popularity = "22.4%" },
            { id = 222440, name = "BiSEverforged Longsword", popularity = "19.9%" },
            { id = 228904, name = "Crowd Favorite", popularity = "15.7%" },
            { id = 234491, name = "BiSSonic Ka-BOOM!-erang", popularity = "14.9%" },
            { id = 232804, name = "Capo's Molten Knuckles", popularity = "9.4%" }
        },
        OFF_HAND = {
            { id = 222441, name = "Everforged Warglaive", popularity = "26.1%" },
            { id = 222440, name = "BiSEverforged Longsword", popularity = "23.5%" },
            { id = 228904, name = "Crowd Favorite", popularity = "14.5%" },
            { id = 234491, name = "BiSSonic Ka-BOOM!-erang", popularity = "8.9%" },
            { id = 232804, name = "Capo's Molten Knuckles", popularity = "7.0%" }
        },
        TRINKET1 = {
            { id = 232541, name = "BiSImprovised Seaforium Pacemaker", popularity = "81.3%" },
            { id = 219309, name = "BiSTome of Light's Devotion", popularity = "45.7%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "18.0%" },
            { id = 232543, name = "BiSRinging Ritual Mud", popularity = "14.7%" },
            { id = 230029, name = "BiSChromebustible Bomb Suit", popularity = "13.2%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "40.6%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "46.8%" },
            { id = 212265, name = "Tempered Potion", popularity = "43.2%" },
            { id = 222720, name = "The Sushi Special", popularity = "37.4%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "75.1%" }
        }
    }
}
