-- Auto-generated by scraper
WishListData_Warrior = {
    PROTECTION = {
        icon = "Interface/ICONS/Ability_Warrior_DefensiveStance",
        talent = "CkEAAAAAAAAAAAAAAAAAAAAAAIGAAAAmZmxMzMYWmZZmZmtFGjZaMLjZYsMmZGWmZGzADDAAAAAAMzAAsstBAsZGDLwAzwCNYB",
        statprio = "Strength > Haste > Crit > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "58.0%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "42.1%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "58.5%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "60.4%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "74.3%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "57.3%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "56.5%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "53.0%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "56.1%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "12.1%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "60.0%" },
            { id = 213455, name = "Quick Ruby", popularity = "45.0%" },
            { id = 213470, name = "Quick Sapphire", popularity = "24.8%" },
            { id = 213485, name = "Versatile Emerald", popularity = "22.0%" },
            { id = 213494, name = "Quick Onyx", popularity = "18.4%" }
        },
        HEAD = {
            { id = 229235, name = "BiSEnforcer's Backalley Faceshield", popularity = "65.2%" },
            { id = 228858, name = "Fullthrottle Facerig", popularity = "6.8%" },
            { id = 222433, name = "Everforged Helm", popularity = "5.7%" },
            { id = 221047, name = "Monstrosity's Gaze", popularity = "5.5%" },
            { id = 221100, name = "Waxsteel Greathelm", popularity = "5.2%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "41.5%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "16.4%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "12.7%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "11.6%" },
            { id = 235429, name = "Moneymaker's Collar", popularity = "2.2%" }
        },
        SHOULDERS = {
            { id = 229233, name = "BiSEnforcer's Backalley Shoulderplates", popularity = "87.6%" },
            { id = 235415, name = "Skyscorcher Pauldrons", popularity = "1.5%" },
            { id = 211982, name = "Warsculptor's Horned Spaulders", popularity = "1.0%" },
            { id = 222436, name = "Everforged Pauldrons", popularity = "0.9%" },
            { id = 235461, name = "Junkreaver's Shoulderplates", popularity = "0.8%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "31.2%" },
            { id = 229230, name = "Enforcer's Backalley Allegiance", popularity = "12.1%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "11.5%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "9.9%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "6.2%" }
        },
        CHEST = {
            { id = 229238, name = "Enforcer's Backalley Vestplate", popularity = "74.1%" },
            { id = 221069, name = "BiSSlashproof Business Plate", popularity = "7.3%" },
            { id = 222430, name = "Everforged Breastplate", popularity = "3.8%" },
            { id = 178793, name = "Abdominal Securing Chestguard", popularity = "1.9%" },
            { id = 228851, name = "\"Bullet-Proof\" Vestplate", popularity = "1.6%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "40.2%" },
            { id = 221064, name = "Fuzzy Cindercuffs", popularity = "11.0%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "11.0%" },
            { id = 228868, name = "Revved-Up Vambraces", popularity = "9.5%" },
            { id = 158359, name = "Stonefury Vambraces", popularity = "5.6%" }
        },
        HANDS = {
            { id = 229236, name = "BiSEnforcer's Backalley Crushers", popularity = "85.4%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "1.8%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "1.4%" },
            { id = 211985, name = "Warsculptor's Crushers", popularity = "1.2%" },
            { id = 221112, name = "Caliginous Claspers", popularity = "1.0%" }
        },
        WAIST = {
            { id = 245966, name = "BiSDurable Information Securing Container", popularity = "91.7%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "1.1%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "1.0%" },
            { id = 221040, name = "Lightning-Conductor's Bands", popularity = "0.6%" },
            { id = 229232, name = "Enforcer's Backalley Girdle", popularity = "0.6%" }
        },
        LEGS = {
            { id = 229234, name = "BiSEnforcer's Backalley Chausses", popularity = "86.6%" },
            { id = 222434, name = "Everforged Legplates", popularity = "1.8%" },
            { id = 221034, name = "Thunder-Clad Legguards", popularity = "1.5%" },
            { id = 211983, name = "Warsculptor's Cuisses", popularity = "1.4%" },
            { id = 178800, name = "Galvanized Oxxein Legguards", popularity = "0.9%" }
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "29.5%" },
            { id = 159679, name = "Sabatons of Rampaging Elements", popularity = "16.7%" },
            { id = 168972, name = "BiSPyroclastic Greatboots", popularity = "7.9%" },
            { id = 229237, name = "Enforcer's Backalley Stompers", popularity = "7.7%" },
            { id = 221061, name = "Hops-Laden Greatboots", popularity = "7.2%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "35.4%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "34.2%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "21.1%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "20.6%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "19.4%" }
        },
        MAIN_HAND = {
            { id = 222440, name = "Everforged Longsword", popularity = "33.1%" },
            { id = 228895, name = "Remixed Ignition Saber", popularity = "12.4%" },
            { id = 169608, name = "BiSTearing Sawtooth Blade", popularity = "9.4%" },
            { id = 221096, name = "Rail Rider's Bisector", popularity = "8.5%" },
            { id = 222451, name = "Charged Slicer", popularity = "6.0%" }
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "40.4%" },
            { id = 228889, name = "BiSTitan of Industry", popularity = "15.3%" },
            { id = 221045, name = "Galebreaker Bulwark", popularity = "8.3%" },
            { id = 159663, name = "G0-4W4Y Crowd Repeller", popularity = "7.9%" },
            { id = 178867, name = "Barricade of the Endless Empire", popularity = "7.3%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "65.9%" },
            { id = 219309, name = "Tome of Light's Devotion", popularity = "30.7%" },
            { id = 232543, name = "Ringing Ritual Mud", popularity = "18.8%" },
            { id = 230029, name = "Chromebustible Bomb Suit", popularity = "16.3%" },
            { id = 230027, name = "House of Cards", popularity = "10.9%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "34.8%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "36.2%" },
            { id = 212265, name = "Tempered Potion", popularity = "28.2%" },
            { id = 222720, name = "The Sushi Special", popularity = "33.9%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "63.6%" }
        }
    },
    ARMS = {
        icon = "Interface/ICONS/Ability_Warrior_SavageBlow",
        talent = "CcEAAAAAAAAAAAAAAAAAAAAAAAGmZGzYGzMLz2yyYGAAAAGMNMzsMmhxyYmZsYmZYGMMAAAAAAAMjZbwAsFDYzMGWgBmhNaAL",
        statprio = "Strength > Crit > Haste > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "68.8%" },
            LEGS = { id = 219908, name = "Defender's Armor Kit", popularity = "48.9%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "48.5%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "58.3%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "81.4%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "55.7%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "41.6%" },
            MAINHAND = { id = 223784, name = "Authority of the Depths", popularity = "37.3%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "68.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "8.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.7%" }
        },
        gems = {
            { id = 213455, name = "Quick Ruby", popularity = "65.8%" },
            { id = 213479, name = "Deadly Emerald", popularity = "56.1%" },
            { id = 213494, name = "Quick Onyx", popularity = "27.0%" },
            { id = 213491, name = "Deadly Onyx", popularity = "23.6%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "18.7%" }
        },
        HEAD = {
            { id = 229235, name = "BiSEnforcer's Backalley Faceshield", popularity = "79.1%" },
            { id = 228858, name = "Fullthrottle Facerig", popularity = "7.4%" },
            { id = 222433, name = "Everforged Helm", popularity = "3.0%" },
            { id = 221100, name = "Waxsteel Greathelm", popularity = "1.6%" },
            { id = 235222, name = "Apogee Inventor's Goggles", popularity = "1.6%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "45.6%" },
            { id = 228841, name = "BiSSemi-Charmed Amulet", popularity = "15.6%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "12.3%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "10.0%" },
            { id = 235428, name = "Gobtastic Bling", popularity = "2.2%" }
        },
        SHOULDERS = {
            { id = 229233, name = "BiSEnforcer's Backalley Shoulderplates", popularity = "89.8%" },
            { id = 235415, name = "Skyscorcher Pauldrons", popularity = "1.1%" },
            { id = 222436, name = "Everforged Pauldrons", popularity = "0.8%" },
            { id = 178802, name = "Unyielding Combatant's Pauldrons", popularity = "0.8%" },
            { id = 211034, name = "Secret-Dredger's Mantle", popularity = "0.7%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "50.0%" },
            { id = 229230, name = "Enforcer's Backalley Allegiance", popularity = "9.1%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "9.0%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "5.8%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "5.2%" }
        },
        CHEST = {
            { id = 229238, name = "Enforcer's Backalley Vestplate", popularity = "72.3%" },
            { id = 221069, name = "Slashproof Business Plate", popularity = "7.9%" },
            { id = 222430, name = "Everforged Breastplate", popularity = "5.6%" },
            { id = 228851, name = "BiS\"Bullet-Proof\" Vestplate", popularity = "2.7%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "2.3%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "58.4%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "7.7%" },
            { id = 228868, name = "Revved-Up Vambraces", popularity = "7.2%" },
            { id = 221064, name = "Fuzzy Cindercuffs", popularity = "6.6%" },
            { id = 158359, name = "Stonefury Vambraces", popularity = "4.1%" }
        },
        HANDS = {
            { id = 229236, name = "BiSEnforcer's Backalley Crushers", popularity = "83.0%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "3.8%" },
            { id = 168980, name = "Gauntlets of Absolute Authority", popularity = "2.0%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "1.8%" },
            { id = 228849, name = "Dumpmech Compactors", popularity = "1.2%" }
        },
        WAIST = {
            { id = 245966, name = "BiSDurable Information Securing Container", popularity = "92.7%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "1.1%" },
            { id = 229232, name = "Enforcer's Backalley Girdle", popularity = "0.6%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "0.5%" },
            { id = 168976, name = "Automatic Waist Tightener", popularity = "0.4%" }
        },
        LEGS = {
            { id = 229234, name = "BiSEnforcer's Backalley Chausses", popularity = "87.1%" },
            { id = 222434, name = "Everforged Legplates", popularity = "2.0%" },
            { id = 159451, name = "Leadplate Legguards", popularity = "1.5%" },
            { id = 221034, name = "Thunder-Clad Legguards", popularity = "0.9%" },
            { id = 178800, name = "Galvanized Oxxein Legguards", popularity = "0.9%" }
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "29.8%" },
            { id = 159679, name = "Sabatons of Rampaging Elements", popularity = "16.6%" },
            { id = 229237, name = "Enforcer's Backalley Stompers", popularity = "9.9%" },
            { id = 228874, name = "Rik's Walkin' Boots", popularity = "9.0%" },
            { id = 228887, name = "BiSCutthroat Competition Stompers", popularity = "6.7%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "58.9%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "31.7%" },
            { id = 228840, name = "BiSFaded Championship Ring", popularity = "17.7%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "16.8%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "16.7%" }
        },
        MAIN_HAND = {
            { id = 222447, name = "Charged Claymore", popularity = "25.7%" },
            { id = 232526, name = "BiSBest-in-Slots", popularity = "25.2%" },
            { id = 222443, name = "Everforged Greataxe", popularity = "8.6%" },
            { id = 178866, name = "Dessia's Decimating Decapitator", popularity = "5.1%" },
            { id = 221038, name = "Crashing Thunderhammer", popularity = "4.9%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "74.1%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "58.3%" },
            { id = 234217, name = "Funhouse Lens", popularity = "11.9%" },
            { id = 219308, name = "Signet of the Priory", popularity = "9.2%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "8.6%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "59.9%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "37.4%" },
            { id = 212265, name = "Tempered Potion", popularity = "54.4%" },
            { id = 222720, name = "The Sushi Special", popularity = "29.6%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "71.3%" }
        }
    },
    FURY = {
        icon = "Interface/ICONS/Ability_Warrior_BattleShout",
        talent = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0YYMLjZYsMmZmFmZmxMYYmltZGzMzGmZmZGmZsMMYGDAAAEGYDWWMaMDgZBGLA",
        statprio = "Strength > Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "65.9%" },
            LEGS = { id = 219908, name = "Defender's Armor Kit", popularity = "47.0%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "48.4%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "58.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "80.5%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "48.4%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "37.3%" },
            MAINHAND = { id = 223784, name = "Authority of the Depths", popularity = "47.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "61.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "7.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.7%" }
        },
        gems = {
            { id = 213494, name = "Quick Onyx", popularity = "55.5%" },
            { id = 213482, name = "Masterful Emerald", popularity = "46.6%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "30.5%" },
            { id = 213458, name = "Masterful Ruby", popularity = "26.8%" },
            { id = 213455, name = "Quick Ruby", popularity = "18.8%" }
        },
        HEAD = {
            { id = 229235, name = "BiSEnforcer's Backalley Faceshield", popularity = "85.9%" },
            { id = 222433, name = "Everforged Helm", popularity = "2.4%" },
            { id = 228858, name = "Fullthrottle Facerig", popularity = "1.6%" },
            { id = 221100, name = "Waxsteel Greathelm", popularity = "1.4%" },
            { id = 235222, name = "Apogee Inventor's Goggles", popularity = "1.1%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "36.9%" },
            { id = 221060, name = "BiSStrapped Rescue-Keg", popularity = "28.6%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "7.8%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "6.1%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "5.5%" }
        },
        SHOULDERS = {
            { id = 229233, name = "BiSEnforcer's Backalley Shoulderplates", popularity = "86.5%" },
            { id = 178802, name = "Unyielding Combatant's Pauldrons", popularity = "1.7%" },
            { id = 228855, name = "Paydirt Pauldrons", popularity = "1.5%" },
            { id = 235415, name = "Skyscorcher Pauldrons", popularity = "1.1%" },
            { id = 222436, name = "Everforged Pauldrons", popularity = "1.0%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "39.8%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "15.4%" },
            { id = 229230, name = "Enforcer's Backalley Allegiance", popularity = "8.3%" },
            { id = 228844, name = "Test Pilot's Go-Pack", popularity = "5.9%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "5.2%" }
        },
        CHEST = {
            { id = 229238, name = "BiSEnforcer's Backalley Vestplate", popularity = "87.9%" },
            { id = 222430, name = "Everforged Breastplate", popularity = "1.4%" },
            { id = 228851, name = "\"Bullet-Proof\" Vestplate", popularity = "1.3%" },
            { id = 221069, name = "Slashproof Business Plate", popularity = "1.2%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "1.1%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "54.3%" },
            { id = 158359, name = "Stonefury Vambraces", popularity = "7.5%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "5.9%" },
            { id = 228868, name = "Revved-Up Vambraces", popularity = "5.2%" },
            { id = 229231, name = "Enforcer's Backalley Bindings", popularity = "4.6%" }
        },
        HANDS = {
            { id = 229236, name = "BiSEnforcer's Backalley Crushers", popularity = "81.6%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "5.1%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "2.9%" },
            { id = 168980, name = "Gauntlets of Absolute Authority", popularity = "1.1%" },
            { id = 228849, name = "Dumpmech Compactors", popularity = "1.1%" }
        },
        WAIST = {
            { id = 245966, name = "BiSDurable Information Securing Container", popularity = "91.4%" },
            { id = 221040, name = "Lightning-Conductor's Bands", popularity = "1.0%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "0.8%" },
            { id = 229232, name = "Enforcer's Backalley Girdle", popularity = "0.5%" },
            { id = 228873, name = "Heaviestweight Title Belt", popularity = "0.5%" }
        },
        LEGS = {
            { id = 229234, name = "Enforcer's Backalley Chausses", popularity = "67.1%" },
            { id = 178800, name = "Galvanized Oxxein Legguards", popularity = "6.7%" },
            { id = 221034, name = "BiSThunder-Clad Legguards", popularity = "5.7%" },
            { id = 222434, name = "Everforged Legplates", popularity = "5.0%" },
            { id = 168966, name = "Heavy Alloy Legplates", popularity = "2.6%" }
        },
        FEET = {
            { id = 229237, name = "Enforcer's Backalley Stompers", popularity = "25.5%" },
            { id = 222429, name = "Everforged Sabatons", popularity = "20.2%" },
            { id = 228874, name = "Rik's Walkin' Boots", popularity = "13.9%" },
            { id = 221123, name = "BiSDevoted Plate Walkers", popularity = "8.9%" },
            { id = 221061, name = "Hops-Laden Greatboots", popularity = "5.9%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "64.1%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "29.2%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "25.5%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "17.8%" },
            { id = 221200, name = "BiSRadiant Necromancer's Band", popularity = "8.9%" }
        },
        MAIN_HAND = {
            { id = 222447, name = "Charged Claymore", popularity = "23.5%" },
            { id = 232526, name = "BiSBest-in-Slots", popularity = "18.0%" },
            { id = 221111, name = "Poleaxe of Somber Fate", popularity = "7.1%" },
            { id = 222443, name = "Everforged Greataxe", popularity = "7.0%" },
            { id = 234490, name = "Circuit Breaker", popularity = "6.7%" }
        },
        OFF_HAND = {
            { id = 222447, name = "Charged Claymore", popularity = "22.4%" },
            { id = 232526, name = "BiSBest-in-Slots", popularity = "14.2%" },
            { id = 228891, name = "BiSCapital Punisher", popularity = "12.2%" },
            { id = 222443, name = "Everforged Greataxe", popularity = "8.8%" },
            { id = 234490, name = "Circuit Breaker", popularity = "5.5%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "67.2%" },
            { id = 230027, name = "House of Cards", popularity = "51.5%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "11.9%" },
            { id = 232485, name = "Mechano-Core Amplifier", popularity = "9.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "9.6%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "57.1%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "34.3%" },
            { id = 212265, name = "Tempered Potion", popularity = "49.8%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "10.6%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "64.1%" }
        }
    }
}
