-- Auto-generated by scraper
WishListData_Rogue = {
    ASSASSINATION = {
        icon = "Interface/ICONS/Ability_Rogue_DeadlyBrew",
        talent = "CMQAAAAAAAAAAAAAAAAAAAAAAYmZMzMmBAAAAAAYWMmlZAAAAAAotlZmBzMGzMzysNYMmZmZmZmZYzyYGgNzyADYBsNMBGWGA",
        statprio = "Mastery > Crit > Haste > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "52.7%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "82.8%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "58.6%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "68.1%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "81.4%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "49.4%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "57.4%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "77.6%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "75.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "3.0%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.1%" }
        },
        gems = {
            { id = 213491, name = "Deadly Onyx", popularity = "62.4%" },
            { id = 213458, name = "Masterful Ruby", popularity = "58.4%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "28.9%" },
            { id = 213482, name = "Masterful Emerald", popularity = "25.4%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "19.9%" }
        },
        HEAD = {
            { id = 229289, name = "BiSSpectral Gambler's Damned Visage", popularity = "74.4%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "6.0%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "3.3%" },
            { id = 228848, name = "Darkfuse Racketeer's Tricorne", popularity = "2.9%" },
            { id = 235419, name = "High Altitude Turban", popularity = "2.3%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "53.8%" },
            { id = 221103, name = "BiSFlickering Glowtorc", popularity = "13.7%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "7.4%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "3.7%" },
            { id = 235428, name = "Gobtastic Bling", popularity = "3.5%" }
        },
        SHOULDERS = {
            { id = 229287, name = "BiSSpectral Gambler's Bladed Mantle", popularity = "89.5%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "1.1%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "0.9%" },
            { id = 212036, name = "K'areshi Phantom's Shoulderpads", popularity = "0.8%" },
            { id = 235811, name = "Extravagant Epaulets", popularity = "0.7%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "31.3%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "15.0%" },
            { id = 234507, name = "BiSElectrician's Siphoning Filter", popularity = "8.9%" },
            { id = 229284, name = "Spectral Gambler's Shawl", popularity = "7.7%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "6.8%" }
        },
        CHEST = {
            { id = 229292, name = "Spectral Gambler's Vest", popularity = "79.8%" },
            { id = 235417, name = "BiSVenture Co. Plenipotentiary Vest", popularity = "6.0%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "3.5%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "1.2%" },
            { id = 228864, name = "\"Streamlined\" Cartel Uniform", popularity = "1.2%" }
        },
        WRISTS = {
            { id = 219334, name = "Rune-Branded Armbands", popularity = "44.9%" },
            { id = 234499, name = "BiSDisturbed Kelp Wraps", popularity = "10.7%" },
            { id = 228869, name = "Killer Queen's Wristflickers", popularity = "8.8%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "8.4%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "5.8%" }
        },
        HANDS = {
            { id = 229290, name = "BiSSpectral Gambler's Gloves", popularity = "72.1%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "5.2%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "4.5%" },
            { id = 159305, name = "Corrosive Handler's Gloves", popularity = "4.3%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "3.7%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "92.9%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "0.5%" },
            { id = 221107, name = "Gleamkeeper's Buckle", popularity = "0.5%" },
            { id = 168957, name = "Mekgineer's Championship Belt", popularity = "0.5%" },
            { id = 159725, name = "Unscrupulous Geologist's Belt", popularity = "0.5%" }
        },
        LEGS = {
            { id = 229288, name = "BiSSpectral Gambler's Pantaloons", popularity = "89.5%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.1%" },
            { id = 178801, name = "Fearless Challenger's Leggings", popularity = "1.0%" },
            { id = 211018, name = "Treasure-Seeker's Breeches", popularity = "1.0%" },
            { id = 221114, name = "Shadowspawn Leggings", popularity = "0.7%" }
        },
        FEET = {
            { id = 219327, name = "BiSRune-Branded Kickers", popularity = "42.6%" },
            { id = 228888, name = "Rushed Beta Launchers", popularity = "9.8%" },
            { id = 221071, name = "Backbreaking Bootstrappers", popularity = "7.7%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "6.4%" },
            { id = 178797, name = "Vanquished Usurper's Footpads", popularity = "5.6%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "68.0%" },
            { id = 228411, name = "BiSCyrce's Circlet", popularity = "36.2%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "21.5%" },
            { id = 221198, name = "85-Year Tenure Ring", popularity = "12.9%" },
            { id = 178869, name = "Fleshfused Circle", popularity = "11.3%" }
        },
        MAIN_HAND = {
            { id = 222438, name = "BiSEverforged Stabber", popularity = "41.2%" },
            { id = 228897, name = "Pyrotechnic Needle-Dropper", popularity = "16.8%" },
            { id = 231266, name = "BiSRandom Number Perforator", popularity = "10.6%" },
            { id = 168962, name = "Apex Perforator", popularity = "8.7%" },
            { id = 221044, name = "Shadowskean of the Colossus", popularity = "7.5%" }
        },
        OFF_HAND = {
            { id = 222438, name = "BiSEverforged Stabber", popularity = "54.6%" },
            { id = 228897, name = "Pyrotechnic Needle-Dropper", popularity = "12.1%" },
            { id = 231266, name = "BiSRandom Number Perforator", popularity = "9.1%" },
            { id = 168962, name = "Apex Perforator", popularity = "4.6%" },
            { id = 221044, name = "Shadowskean of the Colossus", popularity = "4.0%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "73.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "47.6%" },
            { id = 230027, name = "BiSHouse of Cards", popularity = "39.5%" },
            { id = 230198, name = "Eye of Kezan", popularity = "4.3%" },
            { id = 232485, name = "BiSMechano-Core Amplifier", popularity = "4.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "62.4%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "51.4%" },
            { id = 212265, name = "Tempered Potion", popularity = "58.5%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "12.2%" },
            { id = 222504, name = "Ironclaw Whetstone", popularity = "61.5%" }
        }
    },
    OUTLAW = {
        icon = "Interface/ICONS/Ability_Rogue_SinisterCalling",
        talent = "CQQAAAAAAAAAAAAAAAAAAAAAAAAM2mBjZGzMzYYGegxMzMMzMz0yMmtZAAAAAAY2WmZGMzMWglZbAAAAYmZAwY2MMwAzCL0CbGA",
        statprio = "Vers > Haste > Crit > Mastery",
        enchants = {
            HEAD = { id = 238405, name = "Greater Rune of Twilight Devastation", popularity = "62.4%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "82.9%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "57.0%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "67.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "82.9%" },
            RINGS = { id = 223796, name = "Cursed Versatility", popularity = "41.7%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "56.9%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "69.4%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "75.2%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "3.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.1%" }
        },
        gems = {
            { id = 213485, name = "Versatile Emerald", popularity = "58.1%" },
            { id = 213470, name = "Quick Sapphire", popularity = "51.1%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "48.6%" },
            { id = 213461, name = "Versatile Ruby", popularity = "37.2%" },
            { id = 213497, name = "Versatile Onyx", popularity = "21.3%" }
        },
        HEAD = {
            { id = 229289, name = "BiSSpectral Gambler's Damned Visage", popularity = "92.1%" },
            { id = 235224, name = "Mekgineer's Mindbending Headgear", popularity = "1.1%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "0.8%" },
            { id = 212038, name = "K'areshi Phantom's Emptiness", popularity = "0.5%" },
            { id = 224602, name = "Underscout's Cap", popularity = "0.5%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "64.2%" },
            { id = 221103, name = "BiSFlickering Glowtorc", popularity = "13.8%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "3.5%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "3.3%" },
            { id = 235429, name = "Moneymaker's Collar", popularity = "3.0%" }
        },
        SHOULDERS = {
            { id = 229287, name = "BiSSpectral Gambler's Bladed Mantle", popularity = "71.4%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "9.3%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "5.8%" },
            { id = 221201, name = "Fireproof Cinderbee Perch", popularity = "4.3%" },
            { id = 211038, name = "Treasure-Seeker's Epaulets", popularity = "1.3%" }
        },
        BACK = {
            { id = 222817, name = "Consecrated Cloak", popularity = "29.2%" },
            { id = 199921, name = "Trashmaster's Mantle", popularity = "24.2%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "14.7%" },
            { id = 159287, name = "Cloak of Questionable Intent", popularity = "6.8%" },
            { id = 234507, name = "Electrician's Siphoning Filter", popularity = "4.9%" }
        },
        CHEST = {
            { id = 229292, name = "Spectral Gambler's Vest", popularity = "60.6%" },
            { id = 221130, name = "BiSSeraphic Wraps of the Ordained", popularity = "13.5%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "12.0%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "2.0%" },
            { id = 178795, name = "Vest of Concealed Secrets", popularity = "1.9%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "55.1%" },
            { id = 228869, name = "Killer Queen's Wristflickers", popularity = "11.2%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "7.2%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "4.6%" },
            { id = 228885, name = "Hustler's Ante-Uppers", popularity = "3.3%" }
        },
        HANDS = {
            { id = 229290, name = "BiSSpectral Gambler's Gloves", popularity = "90.5%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "1.4%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "0.9%" },
            { id = 211016, name = "Treasure-Seeker's Grips", popularity = "0.8%" },
            { id = 228863, name = "Enforcer's Sticky Fingers", popularity = "0.6%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "93.2%" },
            { id = 221058, name = "Brewery Toiler's Waistband", popularity = "0.8%" },
            { id = 168986, name = "Mad King's Sporran", popularity = "0.5%" },
            { id = 178805, name = "Girdle of Shattered Dreams", popularity = "0.4%" },
            { id = 229286, name = "Spectral Gambler's Pocket Ace", popularity = "0.4%" }
        },
        LEGS = {
            { id = 229288, name = "BiSSpectral Gambler's Pantaloons", popularity = "78.1%" },
            { id = 228854, name = "Bilgerat's Discarded Slacks", popularity = "5.5%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "3.8%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "3.5%" },
            { id = 221114, name = "Shadowspawn Leggings", popularity = "1.4%" }
        },
        FEET = {
            { id = 229291, name = "Spectral Gambler's Cavaliers", popularity = "37.7%" },
            { id = 219327, name = "BiSRune-Branded Kickers", popularity = "19.6%" },
            { id = 228876, name = "Dragster's Last Stride", popularity = "11.7%" },
            { id = 159336, name = "BiSMercenary Miner's Boots", popularity = "8.4%" },
            { id = 168975, name = "Machinist's Treasured Treads", popularity = "4.5%" }
        },
        FINGER1 = {
            { id = 215135, name = "BiSRing of Earthen Craftsmanship", popularity = "70.2%" },
            { id = 221099, name = "BiSWick's Golden Loop", popularity = "28.0%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "16.6%" },
            { id = 228843, name = "BiSMiniature Roulette Wheel", popularity = "9.1%" },
            { id = 178870, name = "Ritual Bone Band", popularity = "8.5%" }
        },
        MAIN_HAND = {
            { id = 232804, name = "BiSCapo's Molten Knuckles", popularity = "29.2%" },
            { id = 222440, name = "Everforged Longsword", popularity = "28.5%" },
            { id = 228904, name = "Crowd Favorite", popularity = "11.9%" },
            { id = 178864, name = "Gorebound Predator's Gavel", popularity = "4.9%" },
            { id = 221033, name = "Hyperactive Stormclaw", popularity = "4.4%" }
        },
        OFF_HAND = {
            { id = 237780, name = "Nightfall Curseblade's Cudgel", popularity = "49.6%" },
            { id = 232804, name = "BiSCapo's Molten Knuckles", popularity = "14.7%" },
            { id = 222440, name = "Everforged Longsword", popularity = "5.9%" },
            { id = 228904, name = "Crowd Favorite", popularity = "5.8%" },
            { id = 222438, name = "Everforged Stabber", popularity = "4.9%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "60.2%" },
            { id = 230189, name = "Junkmaestro's Mega Magnet", popularity = "28.0%" },
            { id = 230197, name = "Geargrinder's Spare Keys", popularity = "26.3%" },
            { id = 219304, name = "Conductor's Wax Whistle", popularity = "18.5%" },
            { id = 230027, name = "House of Cards", popularity = "12.1%" }
        },
        consumables = {
            { id = 212277, name = "Flask of Tempered Versatility", popularity = "69.7%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "53.2%" },
            { id = 212265, name = "Tempered Potion", popularity = "57.3%" },
            { id = 222720, name = "The Sushi Special", popularity = "34.6%" },
            { id = 222504, name = "Ironclaw Whetstone", popularity = "24.5%" },
            { id = 222510, name = "Ironclaw Weightstone", popularity = "24.5%" }
        }
    },
    SUBTLETY = {
        icon = "Interface/ICONS/Ability_Stealth",
        talent = "CUQAAAAAAAAAAAAAAAAAAAAAAAAM2mBAAAAAgZZMWmGzYmxMzYMDzMjhxsNLGzstMzMmZmBMWmtBAAAgZwAYMbGGYgZhFaxGM",
        statprio = "Mastery > Vers > Crit > Haste",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "42.4%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "79.0%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "52.1%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "63.1%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "80.7%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "53.5%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "50.8%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "57.6%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "76.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "3.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        gems = {
            { id = 213497, name = "Versatile Onyx", popularity = "64.9%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "47.9%" },
            { id = 213458, name = "Masterful Ruby", popularity = "23.4%" },
            { id = 213491, name = "Deadly Onyx", popularity = "20.0%" },
            { id = 213461, name = "Versatile Ruby", popularity = "19.7%" }
        },
        HEAD = {
            { id = 229289, name = "BiSSpectral Gambler's Damned Visage", popularity = "85.9%" },
            { id = 235419, name = "High Altitude Turban", popularity = "2.6%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "1.7%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "1.6%" },
            { id = 224677, name = "Lockstitch Headgear", popularity = "1.2%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "61.7%" },
            { id = 221103, name = "BiSFlickering Glowtorc", popularity = "16.0%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "3.7%" },
            { id = 228842, name = "Gobfather's Gifted Bling", popularity = "3.2%" },
            { id = 211063, name = "Long-Lost Choker", popularity = "2.0%" }
        },
        SHOULDERS = {
            { id = 229287, name = "BiSSpectral Gambler's Bladed Mantle", popularity = "91.4%" },
            { id = 212036, name = "K'areshi Phantom's Shoulderpads", popularity = "1.2%" },
            { id = 211038, name = "Treasure-Seeker's Epaulets", popularity = "0.7%" },
            { id = 224607, name = "Underscout's Shoulderguards", popularity = "0.7%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "0.4%" }
        },
        BACK = {
            { id = 222817, name = "BiSConsecrated Cloak", popularity = "28.5%" },
            { id = 229284, name = "Spectral Gambler's Shawl", popularity = "21.6%" },
            { id = 199921, name = "Trashmaster's Mantle", popularity = "12.7%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "7.9%" },
            { id = 221054, name = "Chef Chewie's Towel", popularity = "7.6%" }
        },
        CHEST = {
            { id = 229292, name = "BiSSpectral Gambler's Vest", popularity = "90.8%" },
            { id = 235417, name = "Venture Co. Plenipotentiary Vest", popularity = "1.4%" },
            { id = 211037, name = "Treasure-Seeker's Vest", popularity = "1.0%" },
            { id = 221049, name = "Jerkin of Awakened Stone", popularity = "0.9%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "0.9%" }
        },
        WRISTS = {
            { id = 219334, name = "Rune-Branded Armbands", popularity = "46.7%" },
            { id = 228885, name = "BiSHustler's Ante-Uppers", popularity = "14.3%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "7.7%" },
            { id = 221053, name = "Battle-Scarred Fisticuffs", popularity = "5.0%" },
            { id = 158353, name = "Servo-Arm Bindings", popularity = "4.2%" }
        },
        HANDS = {
            { id = 229290, name = "Spectral Gambler's Gloves", popularity = "39.1%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "23.4%" },
            { id = 221036, name = "Tempestwind Handlers", popularity = "8.2%" },
            { id = 168985, name = "Self-Sanitizing Handwraps", popularity = "7.3%" },
            { id = 228863, name = "BiSEnforcer's Sticky Fingers", popularity = "6.6%" }
        },
        WAIST = {
            { id = 245964, name = "BiSDurable Information Securing Container", popularity = "91.8%" },
            { id = 228856, name = "Competitor's Battle Cord", popularity = "1.1%" },
            { id = 229286, name = "Spectral Gambler's Pocket Ace", popularity = "0.7%" },
            { id = 178805, name = "Girdle of Shattered Dreams", popularity = "0.7%" },
            { id = 159725, name = "Unscrupulous Geologist's Belt", popularity = "0.6%" }
        },
        LEGS = {
            { id = 229288, name = "BiSSpectral Gambler's Pantaloons", popularity = "90.5%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "1.0%" },
            { id = 178801, name = "Fearless Challenger's Leggings", popularity = "0.8%" },
            { id = 211018, name = "Treasure-Seeker's Breeches", popularity = "0.8%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "0.8%" }
        },
        FEET = {
            { id = 219327, name = "BiSRune-Branded Kickers", popularity = "45.2%" },
            { id = 229291, name = "Spectral Gambler's Cavaliers", popularity = "11.3%" },
            { id = 228888, name = "Rushed Beta Launchers", popularity = "7.2%" },
            { id = 221071, name = "Backbreaking Bootstrappers", popularity = "4.6%" },
            { id = 159336, name = "Mercenary Miner's Boots", popularity = "4.2%" }
        },
        FINGER1 = {
            { id = 231265, name = "BiSThe Jastor Diamond", popularity = "51.2%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "34.3%" },
            { id = 178870, name = "BiSRitual Bone Band", popularity = "25.5%" },
            { id = 228411, name = "Cyrce's Circlet", popularity = "25.3%" },
            { id = 221200, name = "Radiant Necromancer's Band", popularity = "16.2%" }
        },
        MAIN_HAND = {
            { id = 222438, name = "Everforged Stabber", popularity = "43.2%" },
            { id = 228897, name = "BiSPyrotechnic Needle-Dropper", popularity = "26.4%" },
            { id = 168962, name = "Apex Perforator", popularity = "7.2%" },
            { id = 221044, name = "Shadowskean of the Colossus", popularity = "6.3%" },
            { id = 231266, name = "Random Number Perforator", popularity = "3.6%" }
        },
        OFF_HAND = {
            { id = 222438, name = "Everforged Stabber", popularity = "43.6%" },
            { id = 228897, name = "BiSPyrotechnic Needle-Dropper", popularity = "25.2%" },
            { id = 231266, name = "Random Number Perforator", popularity = "5.3%" },
            { id = 221044, name = "Shadowskean of the Colossus", popularity = "5.3%" },
            { id = 234493, name = "Geezle's Coercive Volt-ohmmeter", popularity = "2.9%" }
        },
        TRINKET1 = {
            { id = 230027, name = "BiSHouse of Cards", popularity = "78.9%" },
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "63.3%" },
            { id = 230198, name = "BiSEye of Kezan", popularity = "8.9%" },
            { id = 219308, name = "Signet of the Priory", popularity = "7.8%" },
            { id = 235363, name = "Suspicious Energy Drink", popularity = "4.2%" }
        },
        consumables = {
            { id = 212277, name = "Flask of Tempered Versatility", popularity = "45.0%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "48.0%" },
            { id = 212265, name = "Tempered Potion", popularity = "55.8%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "13.2%" },
            { id = 222504, name = "Ironclaw Whetstone", popularity = "64.7%" }
        }
    }
}
