name: Scrape and Push Data

on:
  schedule:
    - cron: '21 21 * * *' # every day at midnight UTC+3 (21:21 UTC = 00:21 UTC+3)
  workflow_dispatch:

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python run_scraper.py

      - name: Clone addon repo
        run: git clone https://x-access-token:${{ secrets.ADDON_REPO_TOKEN }}@github.com/umutterol/NemLootTracker.git addon-repo

      - name: Copy data files
        run: cp data/* addon-repo/data/

      - name: Bump version in .toc file
        run: |
          toc_file="addon-repo/NemLootTracker.toc"
          current_version=$(grep -E '^Version:' "$toc_file" | awk '{print $2}')
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i.bak "s/^Version: .*/Version: $new_version/" "$toc_file"
          rm "$toc_file.bak"
          echo "Bumped version: $current_version → $new_version"

      - name: Commit and push to addon repo
        run: |
          cd addon-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/ NemLootTracker.toc
          version=$(grep -E '^Version:' NemLootTracker.toc | awk '{print $2}')
          git commit -m "Automated data update (version $version)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.ADDON_REPO_TOKEN }}@github.com/umutterol/NemLootTracker.git main 